import { notFound } from 'next/navigation'
import Link from 'next/link'
import Breadcrumb from '@/components/Breadcrumb'
import type { Metadata } from 'next'
import { absoluteUrl } from '@/lib/site'
import { truncateForMeta } from '@/lib/format'
import { escapeForJsonLd } from '@/lib/security'

const articles: Record<string, { title: string; seoTitle: string; description: string; tags: string[]; content: string }> = {
  'what-is-a-hers-rater': {
    title: 'What is a HERS Rater? (And When Do You Need One)',
    seoTitle: 'What Is a HERS Rater in California',
    description: 'Learn what a HERS rater is, why California requires them, and when you need one for your construction or renovation project.',
    tags: ['HERS'],
    content: `## The Job in Plain Terms

A HERS (Home Energy Rating System) rater is a certified professional who inspects and tests a home's energy systems to verify compliance with California's Title 24 energy code. Think of a HERS rater as an energy code inspector — like a structural inspector checks framing, a HERS rater checks your HVAC systems, insulation, ductwork, and windows to make sure everything performs as the plans specify.

## What Does a HERS Rater Actually Do?

During a HERS inspection, the rater performs a series of field tests and visual inspections. The most common measures requiring verification include duct leakage testing, airflow measurement, refrigerant charge verification, insulation inspection, and window verification. HERS raters use pressurization equipment to measure how much air leaks from your HVAC ductwork.

## When Do You Need a HERS Rater in California?

You typically need a HERS rater for new residential construction, HVAC system replacements, home additions over a certain square footage, and major renovations with HVAC work.

## HERS vs ECC: What's Changing in 2026?

Starting with the 2025 California Energy Code, the HERS program is being phased out and replaced by the ECC (Energy Code Compliance) program. The role is essentially the same, but the certification and provider structure is changing.
    `,
  },
  'cf2r-vs-cf3r': {
    title: 'CF2R vs CF3R: What\'s the Difference?',
    seoTitle: 'CF2R vs CF3R Explained',
    description: 'Confused about CF2R and CF3R forms? Here\'s a clear explanation of the difference between installer certificates and verifier certificates in California Title 24.',
    tags: ['Forms'],
    content: `## Installer Certificate vs. Verifier Certificate

The CF2R is a declaration by the trade contractor that they installed the specified energy measure correctly. The CF3R is the independent verification signed by a certified HERS or ECC rater after they have personally tested and inspected the installation.

## The Title 24 Compliance Document Chain

To understand CF2R and CF3R forms, you first need to understand how Title 24 documentation flows through a construction project. The CF1R is the compliance report, generated by an energy consultant. The CF2R is the installer certificate, and the CF3R is the verifier certificate.

## Why Both Forms Are Required

California's Title 24 compliance system is built on the principle that self-certification alone isn't sufficient for energy measures. The two-step system creates accountability at both the installation and verification levels.
    `,
  },
  'title-24-compliance-guide': {
    title: 'California Title 24 Compliance: A Builder\'s Guide',
    seoTitle: 'Title 24 Compliance: Builder\'s Guide',
    description: 'A complete guide to California Title 24 energy code compliance for new construction and renovations. Learn what\'s required, who verifies it, and how to stay on schedule.',
    tags: ['Compliance'],
    content: `## Why the Energy Code Lands on the Builder

California's Title 24 Building Energy Efficiency Standards are among the most comprehensive energy codes in the country. For builders, contractors, and developers, understanding what Title 24 requires is essential to keeping projects on schedule.

## What Is Title 24?

Title 24 refers to Part 6 of the California Code of Regulations, which sets minimum energy efficiency standards for all new construction and major renovations in the state.

## The Three Documents Every Project Needs

Title 24 compliance runs on paperwork — specifically, a chain of three documents that must be completed in order: CF1R (Compliance Report), CF2R (Installer Certificate), and CF3R (Verification Certificate).

## How to Keep Your Project on Schedule

Title 24 inspections are a frequent source of construction delays. To stay on track, hire the HERS rater early, brief your trade contractors, schedule insulation inspections before drywall, and get your CF2Rs filed promptly.
    `,
  },
  'what-is-acceptance-testing': {
    title: 'What Does an Acceptance Tester Do?',
    seoTitle: 'Title 24 Acceptance Testing Explained',
    description: 'Learn what Title 24 acceptance testing covers in California, when it\'s required, and how to find a certified acceptance tester for your project.',
    tags: ['Compliance'],
    content: `## Functional Testing Before Occupancy

Acceptance testing is a mandatory part of Title 24 compliance for certain building systems. An acceptance tester is a certified professional who performs standardized functional tests to verify that installed systems operate correctly before a certificate of occupancy is issued.

## What Systems Require Acceptance Testing?

Title 24 acceptance testing covers a range of building systems. The most commonly tested include HVAC controls and economizers, lighting controls, outdoor lighting controls, mechanical ventilation, fault detection and diagnostics, and plumbing controls.

## Who Can Perform Acceptance Testing?

Title 24 acceptance testing must be performed by a certified acceptance test technician (ATT) or an acceptance test employer (ATE). Requirements vary depending on the system being tested and the scope of the project.

## Finding an Acceptance Tester in California

Use our directory to find certified acceptance testers serving your project's location. Filter by the "Acceptance Tester" service type to see qualified professionals in your area.
    `,
  },
  'hers-vs-ecc-rater': {
    title: 'HERS Rater or ECC Rater? Same Role, New Name',
    seoTitle: 'HERS Rater vs ECC Rater',
    description: 'HERS raters and ECC raters are the same role under two names — the 2025 California Energy Code renamed the program. Here is which term applies to your project, and the distinction that does matter.',
    tags: ['HERS', 'ECC'],
    content: `## One Program, Renamed in 2025

They are the same person doing the same job. If you are searching for one and not the other, you are cutting your options in half for no reason.

California's 2025 Energy Code, effective January 1, 2026, renamed the Home Energy Rating System (HERS) program to Energy Code Compliance (ECC). The certification changed name; the work did not. A rater who was certified under HERS is the same rater you hire under ECC.

## What the Rater Actually Does

Whichever name is on the certificate, this is a certified independent field verifier. They come to the site, test and inspect the installed energy measures called out on your CF1R — duct leakage, refrigerant charge, airflow, insulation quality, whole-house ventilation — and sign the CF3R that lets the building department close out the permit.

Independent is the operative word. The rater cannot be the contractor who installed the work, which is exactly why the verification carries weight.

## Which Term Applies to Your Project

It follows the code cycle your permit was pulled under:

- Permitted under the 2022 Energy Code — the paperwork says HERS verification.
- Permitted under the 2025 Energy Code — the paperwork says ECC verification.

Either way you are looking for the same professional, and most active raters carry both. Ask which certification they hold for your code cycle rather than screening on the name.

## The Distinction That Does Matter: Writer vs. Rater

The confusing pair is not HERS versus ECC. It is the person who **writes** the compliance report versus the person who **verifies** it in the field.

- The **ECC Writer**, usually called the Title 24 energy consultant, models your building in approved compliance software and produces the CF1R. This happens before permit, at the design stage.
- The **HERS / ECC Rater** shows up after installation, tests what was built, and signs the CF3R.

Two different people, two different points in the project, and on most California projects you need both. Hiring a rater does not get you a CF1R, and hiring a consultant does not get your permit signed off.

## Finding One

Browse the directory under the **HERS / ECC Rater** service type to see certified verifiers serving your city or county. The listing covers both names, because it is one role.
    `,
  },
  'title-24-solar-requirements': {
    title: 'Title 24 Solar Requirements for New Homes',
    seoTitle: 'Title 24 Solar Requirements',
    description: 'California requires solar panels on most new homes. Learn about Title 24 solar requirements, exceptions, and how compliance is verified.',
    tags: ['Solar', 'Compliance'],
    content: `## Solar on New Homes Since 2020

Since 2020, California has required solar photovoltaic systems on most new residential construction. This mandate, part of the Title 24 Building Energy Efficiency Standards, makes California the first state in the nation to require solar on new homes.

## What Does the Solar Mandate Require?

The Title 24 solar requirement applies to all new single-family homes, duplexes, and low-rise multifamily buildings (three stories or fewer). The minimum system size is calculated based on the home's conditioned floor area and climate zone. For a typical single-family home, this usually means a 2-4 kW system.

## Are There Exceptions?

Yes. Homes with significant roof shading from existing structures or trees may qualify for a reduction or exemption. Properties where the annual solar access is less than 80 percent of optimal can also receive adjustments. Additionally, homes in certain climate zones with community shared solar programs may use off-site solar to meet the requirement.

## How Is Solar Compliance Verified?

Solar compliance is documented on the CF1R energy compliance report and verified through building department plan review. The installed system must match or exceed the specifications in the compliance documents. Final inspection confirms the system is installed and operational before certificate of occupancy is issued.
`,
  },
  'what-is-a-cf1r': {
    title: 'What Is a CF1R? The First Step in Title 24 Compliance',
    seoTitle: 'What Is a CF1R Form?',
    description: 'The CF1R is the foundation of Title 24 compliance. Learn what it is, who prepares it, and why it matters for your California construction project.',
    tags: ['Forms', 'Compliance'],
    content: `## The Certificate of Compliance, Defined

The CF1R, or Certificate of Compliance, is the first document in California's Title 24 energy compliance chain. It is an energy model and report generated by an energy consultant that demonstrates how a proposed building design will meet or exceed the state's energy efficiency standards.

## Who Prepares the CF1R?

The CF1R is typically prepared by a Title 24 energy consultant using approved compliance software such as CBECC-Res for residential projects or CBECC-Com for commercial buildings. The consultant models the building's envelope, HVAC systems, water heating, lighting, and solar to produce a report showing code compliance.

## What Does the CF1R Include?

The CF1R includes the building's energy budget calculations, a list of required HERS or ECC verification measures (CF3R items), specifications for installed equipment, insulation R-values, window U-factors and SHGC ratings, and duct system requirements. It serves as the blueprint that contractors must follow and verifiers must check against.

## Why the CF1R Matters for Your Project

Without an approved CF1R, your building permit will not be issued. The CF1R also determines which field verification tests your project will require. Getting the CF1R done early allows your team to plan for inspections, order the right equipment, and avoid costly change orders later in construction.
`,
  },
  'duct-leakage-testing': {
    title: 'Duct Leakage Testing: What It Is and Why It Matters',
    seoTitle: 'Duct Leakage Testing in California',
    description: 'Duct leakage testing is one of the most common Title 24 HERS verification measures. Learn how it works, what the limits are, and how to pass.',
    tags: ['HERS', 'Testing'],
    content: `## Why This Test Shows Up on So Many Projects

Duct leakage testing is a diagnostic procedure that measures how much conditioned air escapes from your HVAC ductwork before reaching the living space. In California, duct leakage testing is one of the most frequently required HERS verification measures under Title 24.

## How Is Duct Leakage Measured?

A HERS rater uses a calibrated fan and pressure gauge called a duct blaster to pressurize the duct system to 25 Pascals. The fan speed required to maintain that pressure indicates the leakage rate, measured in cubic feet per minute (CFM25). This value is then compared against the maximum allowed by the CF1R energy compliance report.

## What Are the Leakage Limits?

For new construction in California, total duct leakage must typically not exceed 4 percent of the nominal system airflow. For HVAC replacements and alterations, the requirement may be 8 percent or 15 percent depending on the scope of work and accessibility of the duct system.

## Tips for Passing Duct Leakage Testing

Seal all duct joints with mastic or approved tape before the test. Pay special attention to connections at the air handler, register boots, and takeoffs. Flex duct connections should be secured with zip ties and sealed with mastic. Schedule the test before drywall is installed so any leaks can be easily located and repaired.
`,
  },
  'heat-pump-water-heater-title-24': {
    title: 'Heat Pump Water Heaters and Title 24 Compliance',
    seoTitle: 'Heat Pump Water Heaters Under Title 24',
    description: 'Heat pump water heaters are increasingly required by Title 24. Learn about the requirements, energy savings, and compliance verification process.',
    tags: ['Compliance', 'HERS'],
    content: `## How HPWHs Became the Baseline

The 2022 Energy Code made the heat pump water heater (HPWH) the baseline for single-family new construction. Baseline means the energy budget your design is scored against already assumes one, so specifying a gas or electric-resistance tank is not prohibited outright — it just puts you in a hole you have to dig out of with efficiency elsewhere in the building. In practice that made HPWHs the default on most new homes.

The 2025 Energy Code extends the same framing rather than replacing it, carrying heat pump water heating into multifamily construction. If you built to the 2022 code on the single-family side, the 2025 cycle is a widening of ground you already know.

## Why Heat Pump Water Heaters?

Heat pump water heaters use electricity to move heat from the surrounding air into the water tank, making them two to three times more energy efficient than conventional electric resistance or gas water heaters. This efficiency gain is critical for meeting California's aggressive energy and carbon reduction goals.

## Title 24 Verification Requirements

When a heat pump water heater is installed, the HERS or ECC rater may need to verify proper installation including correct placement for adequate airflow, proper condensate drainage, appropriate electrical connections, and that the unit matches the specifications listed on the CF1R compliance report. Some installations also require verification of the dedicated 240-volt circuit and proper clearances.

## Installation Considerations

Heat pump water heaters need adequate airspace around them to operate efficiently. California's building code requires a minimum room volume or louvered door for enclosed installations. They also produce cool, dehumidified air as a byproduct, which can be beneficial in warm climates but should be considered in cooler regions.
`,
  },
  'performance-path-title-24': {
    title: 'Performance Path vs. Prescriptive Path: Title 24 Compliance Methods',
    seoTitle: 'Title 24 Performance vs Prescriptive',
    description: 'California Title 24 offers two compliance approaches. Learn the difference between performance and prescriptive paths and which is right for your project.',
    tags: ['Compliance'],
    content: `## Two Ways to Show Compliance

California's Title 24 energy code offers two methods for demonstrating compliance: the prescriptive path and the performance path. Understanding the difference is important for builders, architects, and energy consultants because the choice affects design flexibility, cost, and the verification measures required.

## What Is the Prescriptive Path?

The prescriptive path is a checklist approach. It specifies exact minimum requirements for each building component: insulation R-values, window U-factors, HVAC efficiency ratings, lighting power density, and more. If every component meets or exceeds the prescribed value, the building complies. No energy modeling is required.

## What Is the Performance Path?

The performance path uses computer energy modeling to demonstrate that the proposed building design will use equal or less energy than a standard reference design. This approach allows trade-offs between building components. For example, a designer might use higher-performance windows to offset lower insulation values, as long as the total energy budget is met.

## Which Path Should You Choose?

The prescriptive path is simpler but less flexible. It works well for straightforward projects with standard designs. The performance path requires an energy consultant and modeling software but offers significantly more design freedom. Most custom homes and larger projects use the performance path because it allows optimization and often results in lower construction costs through strategic trade-offs.
`,
  },
  'adu-title-24-requirements': {
    title: 'Title 24 for ADUs: What California Homeowners Need to Know',
    seoTitle: 'ADU Title 24 Requirements in California',
    description: 'Building an ADU in California? What Title 24 requires for detached, attached and garage-conversion ADUs, when solar is mandatory, and which HERS tests to expect.',
    tags: ['ADU', 'Compliance'],
    content: `## Every Permitted ADU Needs Title 24

If your ADU is site-built or factory-built and needs a building permit, it needs to show compliance with California's energy code (Title 24, Part 6). HUD-code manufactured homes follow a different set of state rules. In practice that means a CF1R compliance report submitted with your plans, installer certificates (CF2R) from the trades, and field verification by a certified HERS or ECC rater (CF3R) for any measures the CF1R flags for testing. When field verification is required, the building department will not sign off final inspection until that paperwork is complete and registered.

## How Your ADU Type Changes the Rules

The energy code does not have a separate ADU chapter. Instead, your ADU is treated like whatever it physically is. A newly constructed detached ADU is treated as new single-family construction. An attached ADU that adds new floor area is generally treated as an addition to the existing house. A garage conversion turns unconditioned space into conditioned space, which is also generally handled as an addition. Converting space that is already conditioned, such as a bonus room or part of the main house, is usually handled as an alteration.

That classification drives almost everything else: which requirements apply, whether solar is required, and how much testing a HERS or ECC rater has to do. Confirm the classification with your energy consultant and building department before you finalize plans.

## Does My ADU Need Solar Panels?

Under the solar PV requirement in Section 150.1(c)14, newly constructed detached ADUs generally must include a solar PV system sized by the code formula. Attached ADUs, garage conversions and conversions of existing space generally do not trigger the new-construction PV requirement because they are additions or alterations, not new buildings.

There are exceptions even for detached ADUs. The most common are limited solar access (less than 80 contiguous square feet of usable roof), and a calculated minimum system size below 1.8 kWdc, which small ADUs in mild climate zones sometimes hit. Your CF1R will show whether PV is required and at what size.

## Which HERS Tests Should You Expect?

Your CF1R has the final list. For a 2025-code ADU it commonly includes duct leakage testing if you have ducted heating or cooling, airflow and fan efficacy checks on ducted systems, refrigerant charge verification on heat pumps (and on air conditioners in Climate Zones 2 and 8 through 15), and verification of measures like Quality Insulation Installation (QII). A new ADU dwelling unit also needs its whole-house ventilation airflow and its kitchen range hood verified, even if it has no ducts. A ductless mini-split has no ducts to leakage-test, so it usually means fewer field tests than a ducted system, but it still needs refrigerant charge verification and anything else the CF1R lists.

QII is the one that catches people out. Under the 2025 prescriptive rules it applies to new detached ADUs in every climate zone and to additions over 700 square feet. Additions of 700 square feet or less are exempt unless the energy model takes credit for QII. Either way, the rater has to inspect at framing and again before drywall goes up. Miss that window and you may have to open walls or redo the energy calculations.

## Heat Pumps Are the Baseline

For a new detached ADU, the 2025 code's baseline uses a heat pump for both space heating and water heating in every climate zone. Under the 2022 code (permit applications before January 1, 2026), the baseline used a heat pump for space heating or water heating depending on climate zone. You can still propose gas equipment on the performance path, but the energy model has to show the project still complies, usually by making up the difference elsewhere. Attached ADUs and conversions follow the addition and alteration rules instead, including separate rules for equipment you keep. For a new detached ADU, an all-electric design (a ductless or small ducted heat pump plus a heat pump water heater) lines up with the 2025 baseline, so it is worth pricing first.

## How to Keep Your ADU on Schedule

Get the CF1R done before plan submittal, not after the first plan check comment. Book your HERS or ECC rater early and tell them whether QII is on the report. Give your HVAC installer the list of tests on the CF1R, such as refrigerant charge and, for ducted systems, duct leakage, and have them complete the CF2R promptly. Leaky ducts and missing paperwork are common reasons a verification gets held up, and both are easier to fix before the rater arrives than after.
`,
  },
  'hers-test-cost': {
    title: 'How Much Does a HERS Test Cost in California?',
    seoTitle: 'HERS Test Cost in California',
    description: 'What HERS and ECC verification typically costs in California for an HVAC changeout, an ADU or a new home, what drives the price, and how to avoid paying for a retest.',
    tags: ['HERS', 'Cost'],
    content: `## The Short Answer

There is no set price. HERS and ECC raters are private businesses, and what you pay depends on how many measures your project needs verified, how many systems are involved and where the job is. As a rough guide, the publicly posted California prices we found for a single-system HVAC changeout verification ranged from a few hundred dollars to around a thousand, depending on home size and how many tests are bundled, while projects with several measures, like many new homes and ADUs, cost more. Treat any number you see online, including these, as a starting point for getting quotes, not a promise.

## What You Are Actually Paying For

A HERS or ECC quote mostly follows the work on your CF1R or permit: which measures need verifying, how many systems, and how many trips. Some raters also price certain tests, like duct leakage, in square-footage brackets. Each verified measure takes equipment, time on site and data entry in a CEC-approved registry. The common ones are duct leakage testing, refrigerant charge verification, airflow and fan efficacy measurements, blower door testing, and Quality Insulation Installation (QII) inspections. A changeout with one system and one duct test is a short visit. A new home with QII, a blower door test, two HVAC systems and a heat pump water heater can mean multiple trips.

## What Drives the Price Up

Number of systems is a big factor. Each additional independent HVAC system usually adds testing, so ask the rater how they count systems (a furnace and condenser working together are typically one system). Multiple site visits add cost, and QII alone usually means at least one extra trip because the insulation has to be inspected before drywall. Registry fees are often built into the quote but are sometimes listed separately, so ask. Travel distance matters too: a rater who has to drive two hours will price that in. Finally, retests. If your ducts fail leakage testing or the refrigerant charge is off, the problem has to be fixed and re-verified. Sometimes that can happen on the same visit; often it means a return trip, so ask what retests and waiting time cost.

## Changeout vs. ADU vs. New Home

For an HVAC changeout, the typical scope is duct leakage plus, depending on the equipment and climate zone, refrigerant charge and airflow verification on one system, and it is usually the least expensive HERS job. An ADU depends on what kind it is: a new detached ADU is treated like a new home, while attached ADUs and conversions follow the addition and alteration rules. Its scope can include QII, ventilation checks and sometimes a blower door test, and a ductless ADU skips the duct test. A new single-family home has the broadest scope and is often quoted as a package, so ask which visits and retests the package includes.

## How to Avoid Paying Twice

Failed tests, waiting time and return visits are where HERS costs climb past the original quote. Have your HVAC contractor seal and pre-test the ducts before the rater arrives. Make sure the installer has completed the CF2R paperwork in the registry, since the rater cannot sign a CF3R against a missing installer certificate. Book the rater early. Have HVAC equipment fully installed before its tests, but schedule QII inspections at the framing and insulation stages, before anything gets covered. Clear access to the attic, the air handler and the condenser. And bundle as many measures into one visit as the construction sequence allows.

## Getting Quotes

Ask each rater for a quote based on your actual CF1R or permit scope, and ask whether it includes registry fees and what a retest costs. Use the directory to find certified raters who serve your city or county, and compare at least two or three.
`,
  },
  '2025-energy-code-changes': {
    title: 'California 2025 Energy Code: What Changed for Homes',
    seoTitle: '2025 Title 24 Energy Code Changes',
    description: 'The 2025 California Energy Code took effect January 1, 2026. The changes that matter for homeowners, builders and HVAC contractors, from HERS becoming ECC to new insulation and window minimums.',
    tags: ['Compliance', 'ECC'],
    content: `## When the 2025 Code Applies

California updates its Building Energy Efficiency Standards (Title 24, Part 6) every three years. The 2025 Energy Code took effect on January 1, 2026. Which code applies to your project depends on when the permit application was submitted, not when construction starts, so projects permitted in late 2025 may still be built under the 2022 rules.

## HERS Raters Are Now ECC Raters

The biggest visible change is a name. Under the 2025 code the field verification program is called ECC, for Energy Code Compliance, and the raters and providers are called ECC raters and ECC providers. The name change doesn't approve anyone automatically: raters are certified for a specific code cycle, and as of October 2026 CHEERS is the approved ECC provider. The job is essentially the same: an independent, certified rater tests and verifies energy measures in the field and signs the CF3R. The CEC has also tightened quality assurance and documentation requirements on providers. For homeowners and contractors, the practical point is that a permit applied for on or after January 1, 2026 uses ECC verification when the scope requires it, while an application submitted before that date stays on the 2022 code and HERS forms, even if the permit is issued in 2026. Ask your rater to confirm they are certified for your project's code cycle.

## Heat Pumps Keep Moving Toward the Baseline

The 2022 code made heat pumps the baseline for new single-family homes, for space heating, water heating or both depending on climate zone. The 2025 code goes further: for new single-family homes, the baseline is now a heat pump for both space heating and water heating in every climate zone. For additions, when an additional water heater is installed as part of the addition, it generally has to be a heat pump water heater (small additions of 500 square feet or less also have an electric point-of-use option), and the gas tankless option the 2022 code allowed is gone. Gas equipment is still allowed in many situations, particularly when you are replacing existing gas equipment in an alteration, but in new work you generally have to compensate for it with other efficiency measures.

## HVAC Sizing and Load Calculations

The 2025 code puts more emphasis on proper sizing. Heating and cooling load calculations, using a method such as ACCA Manual J, are required for new space-conditioning systems, and equipment selection now references ACCA Manual S-2023. Systems serving additions have their own sizing rules, including maximum capacity limits unless airflow is verified. For HVAC contractors that means sizing from the calculated loads, not adding an arbitrary safety margin.

## Insulation and Windows Get Tighter

Minimum wall insulation went up, to R-15 in 2x4 framing and R-21 in 2x6 framing. The prescriptive maximum window U-factor tightened from 0.30 to 0.27 in Climate Zones 1 through 5, 11 through 14 and 16, and stays at 0.30 in Climate Zones 6 through 10 and 15. New dwelling units of 500 square feet or less in Climate Zone 5 can still use 0.30. The solar heat gain limit tightened only in Climate Zone 15 for new construction. Replacement windows in alterations generally follow the same U-factor limits, and in Climate Zone 15 the replacement solar heat gain cap is 0.23. Replacements of 75 square feet or less can instead meet a U-factor of 0.40 and, in Climate Zones 2, 4 and 6 through 15, a solar heat gain coefficient of 0.35, so check the numbers for your climate zone before you order.

## What This Means for Your Project

If you are planning an ADU, addition or new home, check the permit application date first: applications submitted on or after January 1, 2026 use the 2025 rules and software, while earlier applications stay on the 2022 code. If you are replacing HVAC equipment on a 2025-code permit, expect ECC verification for the tests your equipment, ducts and climate zone trigger. And if you are a contractor, the easiest way to avoid delays under the new code is still the old one: sealed ducts, correct charge and complete paperwork before the rater shows up, with any construction-stage inspections booked early.
`,
  },
  'hvac-replacement-hers-rater': {
    title: 'Do You Need a HERS Rater for an HVAC Replacement?',
    seoTitle: 'HERS Rater for HVAC Replacement',
    description: 'Replacing your HVAC system in California? Learn when Title 24 requires a HERS rater inspection and what to expect during the verification process.',
    tags: ['HERS', 'HVAC'],
    content: `## The Short Answer: Usually Yes

In most cases, yes. California's Title 24 energy code requires HERS verification for HVAC system replacements in existing homes. When you replace a furnace, air conditioner, or heat pump, a certified HERS or ECC rater must verify that the new system is installed correctly and meets energy code requirements.

## What Does the HERS Rater Check?

For a typical HVAC replacement, the HERS rater will verify refrigerant charge to ensure the system has the correct amount of refrigerant for optimal efficiency, airflow across the indoor coil to confirm it meets manufacturer specifications, duct leakage to make sure the duct system is adequately sealed, and that the equipment matches what was specified on the compliance documents.

## When Is HERS Verification Required?

HERS verification is required for most HVAC change-outs that require a building permit. This includes replacing a furnace, air conditioner, heat pump, or package unit. Some exceptions exist for like-for-like replacements in certain situations, but the trend under California's updated energy codes is toward more verification, not less.

## How to Prepare for the Inspection

Make sure your HVAC contractor pulls the proper permits and files the CF1R before starting work. The contractor should complete and sign the CF2R installer certificate after installation. Then schedule the HERS rater to perform the CF3R verification. Having all paperwork in order before the rater arrives will help the inspection go smoothly and avoid delays in closing out the permit.
`,
  },
  "refrigerant-charge-verification": {
    title: "Refrigerant Charge Verification (RCV) in California: When It's Required and How It Works",
    seoTitle: "Refrigerant Charge Verification in Title 24",
    description: "When Title 24 requires refrigerant charge verification, how the RA3.2 test works, what changed in 2025, and how R-454B and R-32 systems fit in.",
    tags: ["HVAC", "HERS"],
    content: "## What is refrigerant charge verification?\n\nRefrigerant charge verification (RCV) is a Title 24 field test that confirms an air conditioner or heat pump holds the amount of refrigerant the manufacturer specifies and that its metering device is working. The HVAC installer charges and tests the system, and then an independent ECC-Rater (formerly HERS rater) verifies it. For permits applied for on or after January 1, 2026, the 2025 California Energy Code's prescriptive rules call for RCV on air-source heat pumps in all climate zones and on air-cooled air conditioners in Climate Zones 2 and 8 through 15, with a few equipment exceptions covered below. It applies to new homes and to alterations that replace refrigerant-containing parts. On a performance-path project, follow the verification list on your approved CF1R.\n\nIncorrect charge, whether too much or too little, reduces capacity and efficiency and can shorten compressor life. The test exists because charge problems are common and hard for owners to spot.\n\n## When RCV is required\n\nIn new construction, the prescriptive package in Table 150.1-A of the 2025 Standards marks refrigerant charge verification as required for heat pumps in every climate zone. For air conditioners it is required in Climate Zones 2, 8, 9, 10, 11, 12, 13, 14 and 15. The requirement for heat pumps in every climate zone is new in 2025.\n\nIn existing homes, Section 150.2(b)1F applies when an air conditioner or heat pump is altered by installing or replacing refrigerant-containing components. These are the compressor, condensing coil, evaporator coil, refrigerant metering device or refrigerant piping.\n\nSwapping a condenser and coil during a change-out therefore triggers RCV in the climate zones above. The same alteration also requires all thermostats on the system to be replaced with setback thermostats. The rule covers ducted split systems, ducted packaged systems, small duct high velocity systems and mini-splits.\n\nYou can look up your climate zone and local raters through our [climate zone directory pages](/directory/zone/9). Zone 9 covers much of inland Los Angeles. Duct leakage testing is a separate requirement, explained in our [duct leakage testing guide](/resources/duct-leakage-testing).\n\n## How the test works\n\nThe Reference Residential Appendix RA3.2 defines two procedures.\n\nThe standard charge verification procedure is used when it is 55°F or warmer outside and the system is within the other operating limits in Table RA3.2-1, which include upper outdoor temperature limits and return-air conditions. For systems with a fixed metering device (a piston or capillary tube), the tester measures superheat and compares it to a target from the appendix table or the manufacturer's chart. For systems with a thermostatic expansion valve (TXV) or electronic expansion valve, the tester measures subcooling against the manufacturer's target and checks superheat to confirm the valve works. Installers must hit tighter tolerances than raters to allow for measurement differences. For subcooling, the installer must be within 3°F of target and the rater within 6°F.\n\nThe weigh-in procedure is used when it is below 55°F or when the standard procedure doesn't fit the system. The installer weighs in the charge based on the manufacturer's specification, line set length and indoor coil (RA3.2.3.1). If the system can be tested with the standard procedure, the rater still verifies it that way once conditions allow. When it is below 55°F, the installer can instead elect to have the rater observe the weigh-in (RA3.2.3.2), and the thermostat must then meet Section 110.12. Systems that can't use the standard procedure at all are verified by rater observation of the weigh-in. Observation means the rater has to be on site while the charge goes in, so schedule it before the installation, not after. Weigh-in verification can't use group sampling.\n\nHeat pumps can only be charge-tested in cooling mode. Because charge is read across the coil, minimum airflow is verified at the same time. For alterations the minimum is 300 cubic feet per minute (cfm) per ton, or 250 cfm per ton for small duct high velocity systems. Ducted central systems in new construction generally must meet 350 cfm per ton (250 cfm per ton for small duct high velocity systems) plus a mandatory fan efficacy limit in watts per cfm (0.45 for gas furnaces, 0.58 for other air handlers, 0.62 for small duct high velocity). Our [CF2R vs CF3R guide](/resources/cf2r-vs-cf3r) explains the installer and rater paperwork that records these results.\n\n## Exceptions and special cases\n\n- Factory-charged packaged units. An entirely new or complete replacement packaged system charged and verified by the manufacturer does not need field charge verification. The installer must certify on the CF2R that it was factory charged and not altered. Ducted packaged units still need the airflow check.\n- Mini-splits and systems that can't use the standard test. These follow the weigh-in route with rater verification. The 2025 manual notes that even DIY pre-charged mini-splits need RCV, because connecting the line set at the home alters the system, and that weigh-in is the right method.\n- Low airflow (alterations only). Altered systems that can't meet minimum airflow have an alternative path (RA3.3.3.1.5), but it comes with thermostat requirements and no group sampling. New construction has no such exception.\n\n## The fault indicator display option is gone\n\nOlder code cycles let some systems use a fault indicator display (FID) in place of charge verification. The 2025 Single-Family Compliance Manual states that fault indicator displays \"have been removed as an available method for refrigerant charge verification.\" If your contractor is quoting an FID approach on a 2025-code permit, ask them to confirm it with the building department. In the 2025 code, FIDs now appear in a different role, on HRV and ERV ventilation systems.\n\n## R-454B, R-32 and the refrigerant transition\n\nFederal rules under the AIM Act have been moving new residential air conditioning and heat pump systems away from R-410A to refrigerants with a global warming potential below 700. In practice that means mostly A2L refrigerants such as R-454B and R-32. Under EPA's earlier rules, split systems built from components made before 2025 could only be installed until January 1, 2026. EPA's final rule of May 2026, effective July 27, 2026, removed that installation deadline for systems whose specified components were all made or imported before 2025. California has its own refrigerant rules, so check both before installing leftover inventory.\n\nFor California RCV, a few points matter:\n\n- The RA3.2 procedures are not tied to a specific refrigerant. Subcooling and superheat are read with gauges set for the system's refrigerant and compared against the manufacturer's targets. Which method applies depends on the metering device and the manufacturer's instructions, not on the refrigerant, and some systems need an observed weigh-in.\n- The winter setup alternative in Appendix RA1.2 lists pressure ranges only for R-410A and R-22. Ask your rater how they handle cold-weather verification on an A2L system.\n- A2L refrigerants are mildly flammable, and the equipment comes with its own installation and safety requirements under the mechanical code and the manufacturer's instructions. RCV does not replace those requirements.\n\nRepairing an existing R-410A system is a different situation from installing a new one. Whether a repair triggers RCV depends on which components are replaced, not on the refrigerant type.\n\n## If the system fails\n\nThe installer adjusts the charge or fixes the fault and the rater re-tests. The failure is recorded in the ECC-Provider's registry even if the problem is corrected on the spot. Ask whether a failed test and return visit cost extra, and have the installer charge the system carefully and document the work first. See [typical HERS rater costs](/resources/hers-test-cost).\n\n## Find a rater for refrigerant charge verification\n\nSearch certified raters by city, county or climate zone in the [Title 24 Directory](/directory). If you work in the Inland Empire, try [Riverside County](/directory/county/riverside).",
  },
  "quality-insulation-installation-qii": {
    title: "Quality Insulation Installation (QII): What It Is and How to Pass the Inspection",
    seoTitle: "QII Inspection: Quality Insulation Installation",
    description: "What Title 24 QII is, when it is required for new homes, ADUs and additions, the pre-drywall inspection stages, and the most common reasons it fails.",
    tags: ["Insulation", "HERS"],
    content: "## What is QII?\n\nQuality Insulation Installation (QII) is a Title 24 field verification that checks insulation was installed properly and that the building's air barrier is continuous. It is not enough for the right R-value to be on site. Insulation has to be installed without gaps, voids or excess compression, and air leaks through framing have to be sealed. The insulation installer follows the procedure in Reference Residential Appendix RA3.5, and an ECC-Rater (formerly HERS rater) verifies it in the field, mostly before drywall goes up. Under the 2025 Energy Code, QII is required under the prescriptive path for newly constructed single-family homes in all 16 climate zones.\n\nGaps, voids and compressed batts can cut an insulated wall's real performance well below its label. QII is how the code checks that the insulation and air barrier are installed well enough to support the performance assumed in your energy documents. It is a visual inspection of the installation, not a measurement of the wall's R-value.\n\n## When QII is required, and when it is credited\n\nTable 150.1-A of the 2025 Standards marks QII as required in every climate zone under the prescriptive path for new single-family homes, including detached ADUs. Additions over 700 square feet must meet the Section 150.1(c) prescriptive requirements, with a few addition-specific modifications, and those include QII. When an addition over 700 square feet is a conversion of unconditioned space, such as a garage, QII doesn't require insulating the existing window and door headers, or air sealing where the existing air barrier isn't removed or replaced. For additions of 700 square feet or less, Section 150.2(a)1Bv says QII does not apply.\n\nOn the [performance path](/resources/performance-path-title-24), QII becomes a required ECC verification whenever the energy model includes QII credit. Because QII is part of the prescriptive package, skipping it on a new home generally means making up the difference elsewhere in the model. Your energy consultant can tell you what dropping it would cost.\n\nCheck the ECC or HERS feature summary on your [CF1R](/resources/what-is-a-cf1r). If QII is listed, it is required for your permit.\n\n## What the rater inspects\n\nRA3.5 applies to the whole thermal envelope of a new building, covering walls, ceilings and roofs, and floors. Every insulation type is included, from batts and loose fill to spray foam, rigid board, structural insulated panels (SIPs) and insulating concrete forms (ICFs). The rater checks two things.\n\nThe air barrier. Wall cavities must be caulked, foamed or otherwise sealed against the outdoors, attic, garage and crawlspace. That includes plumbing and wiring penetrations through top and bottom plates, electrical boxes that penetrate the sheathing, and bottom plates sealed to the subfloor or slab.\n\nThe insulation installation. RA3.5 has criteria for each insulation type. Batts and loose fill must fill each cavity side to side, top to bottom and front to back, while spray foam, rigid board and other assemblies have their own thickness, coverage and air-barrier criteria. Batts should touch the sheathing behind and the wallboard in front, with no gaps or voids. They must be cut or split around wiring and plumbing, with compression limited to 30 percent of nominal thickness at obstructions. Narrow spaces at corners and wall intersections must be filled, and single-member window and door headers generally must be insulated (R-3 minimum in 2x4 walls, R-5 in other assemblies). RA3.5 has an exception for a single-member header that is the same width as the wall when the whole wall has at least R-2 insulation.\n\n## When to schedule QII inspections\n\nQII takes more than one visit. Appendix RA2 says the measure requires inspecting the air barrier and the insulation behind tubs and showers at framing rough-in. Wall, floor and ceiling insulation must be verified before drywall, and attic insulation may need a follow-up. A typical sequence:\n\n- Rough-in or framing stage: air sealing at plates and penetrations, insulation and air barrier behind tub and shower enclosures, hard-to-reach cavities at corners. Some of these spots can only be insulated before the tub, exterior sheathing or stucco lath goes on.\n- Insulation stage, before drywall: all wall, floor and ceiling insulation installed and visible.\n- Final or attic stage: blown attic insulation depth and coverage, attic access, and any items deferred from earlier visits.\n\nRater pricing reflects the multiple visits. Some raters quote QII as one price that covers several trips, while others charge per visit, so ask whether your quote covers every stage. See [what a HERS rater costs](/resources/hers-test-cost).\n\nThe biggest scheduling mistake is letting the drywall crew in before the rater signs off on the insulation stage. If walls get closed first, the rater cannot verify them. That can mean opening walls or reworking the compliance approach.\n\n## Common fail points\n\n- Missing or incomplete sealing at top and bottom plates, plumbing and wiring penetrations, and electrical boxes.\n- Uninsulated or poorly insulated spaces behind tubs and showers, with no air barrier on the inside of the exterior wall there.\n- Batts stuffed behind wiring or pipes instead of split around them, leaving compression or voids.\n- Batts not fully filling the cavity front to back, or inset-stapled faced batts left with gaps.\n- Empty narrow cavities at corners, wall intersections and beside window and door jambs.\n- Uninsulated single-member headers that don't qualify for the same-width-as-the-wall exception.\n- Kneewalls, skylight shafts and the house-to-garage wall left without a complete air barrier.\n- Missing insulation certificates or R-value markings for loose fill, such as depth markers in the attic.\n\nFixing these is usually cheap before drywall and expensive after. Give your insulation subcontractor a copy of the RA3.5 criteria and do a walk-through yourself before calling the rater.\n\n## Who does what\n\nThe insulation installer completes the installation certificate (CF2R) and registers it with the ECC-Provider's data registry. The ECC-Rater inspects and registers the certificate of verification (CF3R). The building inspector checks that the registered documents are complete at final. Our guide to [CF2R vs CF3R](/resources/cf2r-vs-cf3r) explains the paperwork.\n\n## Book a QII rater before you frame\n\nQII has to be scheduled around your framing and insulation dates, so line up your rater early. Search certified raters by city, county or climate zone in the [Title 24 Directory](/directory), or start with a local page like [San Bernardino County](/directory/county/san-bernardino).",
  },
  "how-to-find-cf3r-registry": {
    title: "How to Find Your CF2R and CF3R Documents in the California Data Registry",
    seoTitle: "How to Find CF2R and CF3R Registry Documents",
    description: "Where CF2R and CF3R documents are stored, which ECC/HERS registries exist after CalCERTS closed, how to get copies, and what to do if paperwork is missing.",
    tags: ["Forms", "ECC"],
    content: "## How do you find your CF2R and CF3R documents?\n\nCF2R (installation) and CF3R (verification) certificates are stored in the data registry of the ECC-Provider (formerly HERS Provider) your rater used. Today that is almost always CHEERS, or for some HVAC alterations permitted under the 2022 code, Golden State Registry. The CEC does not offer a public registry or lookup service for compliance documents. To get your documents, ask the people who worked on the project: your contractor, builder, energy consultant or ECC-Rater. They can pull the registered PDFs from the registry. Your building department can also look up the project status in the registry by address or permit number.\n\nThe CEC's ECC program page says: \"To obtain copies of a project's documentation, one must coordinate with the builder, installing contractor, rater, or anyone who had a role in the compliance forms process.\" It also notes that \"The CEC does not offer document registration and does not retain compliance documents for public access.\"\n\n## Current registries\n\nAs of October 2026, the CEC lists CHEERS as the approved ECC-Provider for the 2025 code, and Golden State Registry as a HERS Provider for a limited 2022-code scope. CHEERS (California Home Energy Efficiency Rating Services) was approved on November 12, 2025, as an ECC-Provider for the 2025 Energy Code. That covers new single-family and multifamily buildings, additions, alterations, and efficiency measures in dwelling units and mechanical systems in nonresidential buildings. Its registry is also approved for 2013, 2016, 2019 and 2022 code documents.\n\nGolden State Registry (GSR) is approved to oversee raters for prescriptive 2022-code space conditioning alterations and replacements in existing single-family homes. The CEC lists its ECC-Provider application as under review.\n\nCalCERTS is no longer an option. It stopped operating as a HERS Provider on August 2, 2024, and its registry stayed open for document downloads only through September 1, 2024. CHEERS worked with rater companies, energy consultants and builders to move active projects from CalCERTS to the CHEERS registry. The CEC later warned that content on the calcerts.com domain is \"at best, outdated and misleading.\" Don't rely on that site, and don't pay anyone claiming to sell CalCERTS records.\n\nIf you're unsure which registry your project used, look at a document you already have. The registration number, provider name or watermark on a CF1R or CF2R tells you.\n\n## Who can see what in the registry\n\nRegistries are built for professionals. Energy consultants register the CF1R. Installers and builders complete CF2Rs. ECC-Raters complete CF3Rs. Building departments review the project. CHEERS tells building departments to search by project address, homeowner name or permit number and check the project status.\n\nCHEERS offers homeowner accounts, which homeowners can use to sign compliance documents. It also says homeowners should receive a consumer information form, a project owner report and a project status report. Title 24 requires completed documentation to be left in the home for the owner. An ECC-Provider must also send certificates of verification to the homeowner if the owner's contact information is in the registry. If you never got yours, the contact information on file may have been missing or wrong.\n\nFor more on what each form is, see [CF2R vs CF3R](/resources/cf2r-vs-cf3r) and [what is a CF1R](/resources/what-is-a-cf1r).\n\n## How to request copies\n\n- Start with your HVAC contractor or builder. They registered the CF2R and can download the full package.\n- Ask the ECC-Rater whose name is on the CF3R. Raters can pull their own verification records.\n- Ask your building department. It may have the documents in the permit file, or can confirm whether the project shows as complete.\n- Contact the registry directly if the people above are out of business. CHEERS lists help@cheers.org and (800) 424-3377 for support. Have the address, permit number and approximate dates ready.\n\nFor older projects, remember that 2022-cycle and earlier documents say \"HERS\", while 2025-cycle documents say \"ECC\".\n\n## Paperwork missing at final inspection\n\nMissing or incomplete registered documents can keep the building department from signing off at final. Usually the rater hasn't tested yet, the test failed and hasn't been re-done, or the documents were never fully registered. For example, the installer never completed the CF2R the rater needs to finish the CF3R.\n\nWhat to do:\n\n- Ask the contractor for the registry status page. It shows which certificates are complete, pending or failed.\n- If the rater never came out, schedule them now. On HVAC change-outs where the building department doesn't require plans, it may allow the CF1R-ALT-02 to be registered after the permit is issued, but it must be registered before final. Some departments want it before they issue the permit.\n- If a test failed, the contractor has to fix the system and the rater has to re-test. The CEC says the contractor is required to fix the feature until it passes.\n- If the original rater or contractor has disappeared, hire a new certified rater. They can test the system and complete verification, though the project may need to be set up again in the registry and the installer certificates may need to be completed first. Ask your building department what it will accept.\n- Don't let anyone hand you unregistered paper forms for measures that require registration. Building departments need registered documents.\n\nSelling a house with an open HVAC permit can become a negotiation point for buyers. Closing it out with the building department and keeping the registered documents avoids that question when you sell. See our [permit guide for AC and furnace replacements](/resources/hvac-changeout-permit-california).\n\n## Find a rater to finish the job\n\nIf you need a new rater to complete testing or replace one who has stopped responding, search certified ECC and HERS raters by city, county or climate zone in the [Title 24 Directory](/directory). For example, try [San Jose](/directory/san-jose) or [Orange County](/directory/county/orange).",
  },
  "hvac-changeout-permit-california": {
    title: "Do You Need a Permit to Replace an AC or Furnace in California?",
    seoTitle: "Permit to Replace AC or Furnace in California",
    description: "Yes, California requires a permit to replace an AC, heat pump or furnace. Learn who pulls it, what Title 24 tests it triggers, and the risks of skipping it.",
    tags: ["HVAC", "Compliance"],
    content: "## Do you need a permit to replace an AC or furnace in California?\n\nYes. In California, replacing a central air conditioner, heat pump or furnace requires a building or mechanical permit from your city or county, even for a like-for-like swap. The CEC's 2025 Single-Family Residential Compliance Manual states that \"installation of a space conditioning appliance (other than a plug-in room appliance) requires a building permit.\" The change-out itself has to meet Title 24, and the permit is how the building department checks it. The requirements include duct leakage testing and, depending on equipment and climate zone, refrigerant charge and airflow verification by an independent ECC-Rater (formerly HERS rater).\n\nWindow units and other plug-in room appliances are the exception. Hard-wired, ducted, or line-set equipment is generally permitted work; check your building department for any local exemptions. That includes mini-split heat pumps sold as DIY kits.\n\n## Who pulls the permit\n\nNormally the licensed contractor doing the work pulls the permit. The Contractors State License Board (CSLB) advises homeowners to make sure their contractor holds an active C-20 (Warm-Air Heating, Ventilating and Air-Conditioning) license in good standing. You can check the license on the CSLB website.\n\nSome cities let homeowners pull an owner-builder permit for their own home. If you do, you take on the contractor's responsibilities: scheduling the ECC-Rater, completing the installer paperwork and passing the inspections. Ask your building department before you take that route.\n\nA quote with \"no permit needed\" or \"permit optional, saves you money\" is a red flag. An unpermitted change-out skips the inspections that check gas, electrical, venting and condensate work, not just the energy tests.\n\n## What the permit triggers\n\nThe CEC allows an exception for \"urgent alterations (e.g., HVAC changeouts)\": where the building department doesn't require plans with the permit application (Section 10-103), the compliance certificate can be registered after the permit is issued, as long as it happens before final. Some departments still want the compliance certificate registered before issuing the permit. The energy requirements in Section 150.2(b)1 still apply:\n\n- Duct sealing verification. Replacing the air handler, outdoor condensing unit, or cooling or heating coil triggers a duct leakage test on the connected ducts. The limits are 10 percent of system airflow total leakage, or 7 percent leakage to outside. If neither can be met, all accessible leaks are sealed and verified by the rater with a smoke test and visual inspection. Ducts or equipment in a garage have additional sealing requirements. Exceptions include ducts with less than 40 linear feet, ducts already sealed and verified in an earlier test, and ducts made or sealed with asbestos.\n- Refrigerant charge and airflow verification. When refrigerant parts such as the compressor, coils, metering device or piping are replaced, refrigerant charge and minimum airflow (300 cfm per ton for most ducted systems, 250 for small duct high velocity) must be verified. Under the 2025 code (permits applied for on or after January 1, 2026), this applies to air conditioners in Climate Zones 2 and 8 through 15 and to heat pumps in all climate zones. Under the 2022 code, heat pumps were also limited to Climate Zones 2 and 8 through 15. Complete-replacement packaged units charged at the factory are exempt from the charge test (airflow still applies), and performance-path projects follow their CF1R.\n- Setback thermostats. When refrigerant-containing parts of an AC or heat pump are replaced, or the whole system is replaced, all thermostats on that system must be setback thermostats.\n- Complete replacement systems. When the equipment and the duct system are replaced (the code counts a duct system as replaced when at least 75 percent of it is new), more requirements apply, including the new-construction rules for fan power use and airflow (generally 350 cfm per ton with a watts-per-cfm limit), filter requirements, new duct insulation levels and a tighter duct leakage limit.\n- Heating fuel limits. Altered or replacement space heating cannot use electric resistance as the primary heat source, except in limited cases where the existing heat is already electric resistance.\n\nThe full field-test process is covered in our guide on [whether you need a HERS rater for HVAC replacement](/resources/hvac-replacement-hers-rater). Charge testing is covered in [refrigerant charge verification](/resources/refrigerant-charge-verification).\n\n## The paperwork trail\n\nA change-out that needs field verification produces three types of Title 24 documents. The CF1R-ALT-02 certificate of compliance can be registered by final where the building department allows it. The installer's CF2R certificates of installation follow, and then the rater's CF3R certificates of verification. These are registered in an ECC-Provider data registry, and the building inspector checks them before closing the permit. Copies are supposed to be left with the homeowner. If yours are missing, see [how to find CF2R and CF3R documents](/resources/how-to-find-cf3r-registry).\n\n## Permit, testing and duct-work costs\n\nYou'll pay the permit fee, which varies by jurisdiction, and the rater's fee for testing. The published rater prices we found for a typical change-out verification ranged from a few hundred dollars to around a thousand, depending on home size and how many tests are bundled. Our [HERS rater cost guide](/resources/hers-test-cost) has the details. Duct repair is the less obvious cost. If old ducts leak badly, sealing or replacing them can add to the job. Ask your contractor to inspect the ducts and include likely sealing work in the quote.\n\n## What happens if you skip the permit\n\n- Enforcement. A building department that finds unpermitted work can require a permit after the fact. That usually means fees, inspections and possibly opening up work for inspection. Rules and penalties vary by city.\n- Home sale. California's Real Estate Transfer Disclosure Statement (Civil Code Section 1102.6) asks sellers whether they know of \"alterations or repairs made without necessary permits.\" Equipment newer than the last permit on file can come up during a sale and turn into a negotiation point or a request to permit and test the system before closing.\n- Equipment and comfort. Without the required duct test and charge check, nobody independently measures duct leakage or refrigerant charge. Leaky ducts and wrong charge are exactly what the tests are designed to catch.\n- Rebates and financing. Some incentive programs ask for permit or compliance documentation. Read the program rules before you count on a rebate for unpermitted work.\n\n## Find a rater for your change-out\n\nMost contractors already work with a rater, but you can choose your own or compare options. Search certified ECC and HERS raters by city, county or climate zone in the [Title 24 Directory](/directory), or start with [Los Angeles](/directory/los-angeles).",
  },
}

// Article bodies are plain text with two affordances: a paragraph whose every
// line starts with "- " renders as a list, and [text](/path) renders as an
// internal link. Only root-relative hrefs are linked, so article copy can't
// smuggle in an outbound or javascript: URL.
function renderInline(text: string) {
  const parts = text.split(/(\[[^\]]+\]\(\/[^)\s]*\))/g)
  return parts.map((part, i) => {
    const m = part.match(/^\[([^\]]+)\]\((\/[^)\s]*)\)$/)
    if (!m) return part
    return (
      <Link key={i} href={m[2]} className="text-accent underline decoration-accent-rule underline-offset-2 hover:decoration-accent">
        {m[1]}
      </Link>
    )
  })
}

export async function generateStaticParams() {
  return Object.keys(articles).map(slug => ({ slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const article = articles[slug]
  if (!article) return {}
  return {
    title: article.seoTitle,
    // Three of the hand-written descriptions ran past Google's snippet length.
    // Truncating here rather than editing the strings keeps the full sentence
    // for the JSON-LD below and holds new articles to the same limit.
    description: truncateForMeta(article.description),
    alternates: { canonical: absoluteUrl(`/resources/${slug}`) },
  }
}

export default async function ResourceArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const article = articles[slug]
  if (!article) notFound()
  const sections = article.content.split(/^## /gm).filter(Boolean)

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title,
    description: article.description,
    url: absoluteUrl(`/resources/${slug}`),
    publisher: {
      '@type': 'Organization',
      name: 'Title 24 Directory',
      url: absoluteUrl('/'),
    },
  }

  return (
    <div className="mx-auto max-w-3xl px-4 pb-20 pt-12 sm:px-6">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: escapeForJsonLd(jsonLd) }} />

      <Breadcrumb items={[
        { label: 'Home', href: '/' },
        { label: 'Resources', href: '/resources' },
        { label: article.title },
      ]} />

      <article>
        <header className="border-t border-ink pt-6">
          <div className="flex flex-wrap gap-1.5">
            {article.tags.map(tag => (
              <span key={tag} className="tag">{tag}</span>
            ))}
          </div>
          <h1 className="mt-3 text-[clamp(1.75rem,3.6vw,2.5rem)] font-bold leading-[1.08]">
            {article.title}
          </h1>
          <p className="mt-4 max-w-[62ch] text-[1.02rem] leading-relaxed">{article.description}</p>
        </header>

        {/* Body copy is capped at 68ch. The old page ran full-width inside a
            max-w-4xl container, which put long-form prose at ~110 characters
            a line — past the point where the eye reliably finds the next one. */}
        <div className="mt-10 space-y-10">
          {sections.map((section, i) => {
            const lines = section.split('\n')
            const heading = lines[0]
            const body = lines.slice(1).join('\n').trim()
            return (
              <section key={i}>
                <h2 className="text-[1.3rem] font-bold leading-snug">{heading}</h2>
                <div className="mt-3 max-w-[68ch] space-y-4 leading-relaxed">
                  {body.split('\n\n').map((paragraph, j) => {
                    const lines = paragraph.split('\n')
                    if (lines.every(line => line.startsWith('- '))) {
                      return (
                        <ul key={j} className="list-disc space-y-2 pl-5">
                          {lines.map((line, k) => <li key={k}>{renderInline(line.slice(2))}</li>)}
                        </ul>
                      )
                    }
                    return <p key={j}>{renderInline(paragraph)}</p>
                  })}
                </div>
              </section>
            )
          })}
        </div>
      </article>

      <aside className="mt-16 border-t border-ink pt-8">
        <h2 className="text-lg font-bold">Need a rater for this?</h2>
        <p className="mt-2 max-w-[56ch] text-[0.95rem]">
          Search every certified HERS and ECC rater, commissioning agent, and acceptance tester in
          California by city, county, or ZIP.
        </p>
        <div className="mt-5 flex flex-wrap gap-3">
          <Link href="/directory" className="btn-accent px-5 py-2.5 text-sm">
            Find a rater
          </Link>
          <Link href="/resources" className="btn-quiet px-5 py-2.5 text-sm">
            More resources
          </Link>
        </div>
      </aside>
    </div>
  )
}
