import { notFound } from 'next/navigation'
import Link from 'next/link'
import Breadcrumb from '@/components/Breadcrumb'
import type { Metadata } from 'next'

const articles: Record<string, { title: string; seoTitle: string; description: string; tags: string[]; content: string }> = {
  'what-is-a-hers-rater': {
    title: 'What is a HERS Rater? (And When Do You Need One)',
    seoTitle: 'What is a HERS Rater California | Title 24 Directory',
    description: 'Learn what a HERS rater is, why California requires them, and when you need one for your construction or renovation project.',
    tags: ['HERS'],
    content: `## What is a HERS Rater?

A HERS (Home Energy Rating System) rater is a certified professional who inspects and tests a home's energy systems to verify compliance with California's Title 24 energy code. Think of a HERS rater as an energy code inspector â like a structural inspector checks framing, a HERS rater checks your HVAC systems, insulation, ductwork, and windows to make sure everything performs as the plans specify.

## What Does a HERS Rater Actually Do?

During a HERS inspection, the rater performs a series of field tests and visual inspections. The most common measures requiring verification include duct leakage testing, airflow measurement, refrigerant charge verification, insulation inspection, and window verification. HERS raters use pressurization equipment to measure how much air leaks from your HVAC ductwork.

## When Do You Need a HERS Rater in California?

You typically need a HERS rater for new residential construction, HVAC system replacements, home additions over a certain square footage, and major renovations with HVAC work.

## HERS vs ECC: What's Changing in 2026?

Starting with the 2025 California Energy Code, the HERS program is being phased out and replaced by the ECC (Energy Code Compliance) program. The role is essentially the same, but the certification and provider structure is changing.
    `,
  },
  'cf2r-vs-cf3r': {
    title: 'CF2R vs CF3R: What\'s the Difference?',
    seoTitle: 'CF2R vs CF3R Difference | Title 24 California Forms Explained',
    description: 'Confused about CF2R and CF3R forms? Here\'s a clear explanation of the difference between installer certificates and verifier certificates in California Title 24.',
    tags: ['Forms'],
    content: `## CF2R vs CF3R: Understanding Title 24 Compliance Forms

The CF2R is a declaration by the trade contractor that they installed the specified energy measure correctly. The CF3R is the independent verification signed by a certified HERS or ECC rater after they have personally tested and inspected the installation.

## The Title 24 Compliance Document Chain

To understand CF2R and CF3R forms, you first need to understand how Title 24 documentation flows through a construction project. The CF1R is the compliance report, generated by an energy consultant. The CF2R is the installer certificate, and the CF3R is the verifier certificate.

## Why Both Forms Are Required

California's Title 24 compliance system is built on the principle that self-certification alone isn't sufficient for energy measures. The two-step system creates accountability at both the installation and verification levels.
    `,
  },
  'title-24-compliance-guide': {
    title: 'California Title 24 Compliance: A Builder\'s Guide',
    seoTitle: 'California Title 24 Compliance Guide for Builders | Title 24 Directory',
    description: 'A complete guide to California Title 24 energy code compliance for new construction and renovations. Learn what\'s required, who verifies it, and how to stay on schedule.',
    tags: ['Compliance'],
    content: `## California Title 24 Compliance: A Builder's Complete Guide

California's Title 24 Building Energy Efficiency Standards are among the most comprehensive energy codes in the country. For builders, contractors, and developers, understanding what Title 24 requires is essential to keeping projects on schedule.

## What Is Title 24?

Title 24 refers to Part 6 of the California Code of Regulations, which sets minimum energy efficiency standards for all new construction and major renovations in the state.

## The Three Documents Every Project Needs

Title 24 compliance runs on paperwork â specifically, a chain of three documents that must be completed in order: CF1R (Compliance Report), CF2R (Installer Certificate), and CF3R (Verification Certificate).

## How to Keep Your Project on Schedule

Title 24 inspections are a frequent source of construction delays. To stay on track, hire the HERS rater early, brief your trade contractors, schedule insulation inspections before drywall, and get your CF2Rs filed promptly.
    `,
  },
  'what-is-acceptance-testing': {
    title: 'What Does an Acceptance Tester Do?',
    seoTitle: 'Title 24 Acceptance Testing California | What Does an Acceptance Tester Do?',
    description: 'Learn what Title 24 acceptance testing covers in California, when it\'s required, and how to find a certified acceptance tester for your project.',
    tags: ['Compliance'],
    content: `## What Does a Title 24 Acceptance Tester Do?

Acceptance testing is a mandatory part of Title 24 compliance for certain building systems. An acceptance tester is a certified professional who performs standardized functional tests to verify that installed systems operate correctly before a certificate of occupancy is issued.

## What Systems Require Acceptance Testing?

Title 24 acceptance testing covers a range of building systems. The most commonly tested include HVAC controls and economizers, lighting controls, outdoor lighting controls, mechanical ventilation, fault detection and diagnostics, and plumbing controls.

## Who Can Perform Acceptance Testing?

Title 24 acceptance testing must be performed by a certified acceptance test technician (ATT) or an acceptance test employer (ATE). Requirements vary depending on the system being tested and the scope of the project.

## Finding an Acceptance Tester in California

Use our directory to find certified acceptance testers serving your project's location. Filter by the "Acceptance Tester" service type to see qualified professionals in your area.
    `,
  },
  'hers-vs-ecc-rater': {
    title: 'HERS Rater or ECC Rater? Same Role, New Name',
    seoTitle: 'HERS Rater vs ECC Rater California | Same Role, New Name (2026)',
    description: 'HERS raters and ECC raters are the same role under two names — the 2025 California Energy Code renamed the program. Here is which term applies to your project, and the distinction that does matter.',
    tags: ['HERS', 'ECC'],
    content: `## HERS Rater or ECC Rater?

They are the same person doing the same job. If you are searching for one and not the other, you are cutting your options in half for no reason.

California's 2025 Energy Code, effective January 1, 2026, renamed the Home Energy Rating System (HERS) program to Energy Code Compliance (ECC). The certification changed name; the work did not. A rater who was certified under HERS is the same rater you hire under ECC.

## What the Rater Actually Does

Whichever name is on the certificate, this is a certified independent field verifier. They come to the site, test and inspect the installed energy measures called out on your CF1R — duct leakage, refrigerant charge, airflow, insulation quality, whole-house ventilation — and sign the CF3R that lets the building department close out the permit.

Independent is the operative word. The rater cannot be the contractor who installed the work, which is exactly why the verification carries weight.

## Which Term Applies to Your Project

It follows the code cycle your permit was pulled under:

- Permitted under the 2022 Energy Code — the paperwork says HERS verification.
- Permitted under the 2025 Energy Code — the paperwork says ECC verification.

Either way you are looking for the same professional, and most active raters carry both. Ask which certification they hold for your code cycle rather than screening on the name.

## The Distinction That Does Matter: Writer vs. Rater

The confusing pair is not HERS versus ECC. It is the person who **writes** the compliance report versus the person who **verifies** it in the field.

- The **ECC Writer**, usually called the Title 24 energy consultant, models your building in approved compliance software and produces the CF1R. This happens before permit, at the design stage.
- The **HERS / ECC Rater** shows up after installation, tests what was built, and signs the CF3R.

Two different people, two different points in the project, and on most California projects you need both. Hiring a rater does not get you a CF1R, and hiring a consultant does not get your permit signed off.

## Finding One

Browse the directory under the **HERS / ECC Rater** service type to see certified verifiers serving your city or county. The listing covers both names, because it is one role.
    `,
  },
  'title-24-solar-requirements': {
    title: 'Title 24 Solar Requirements for New Homes',
    seoTitle: 'California Title 24 Solar Requirements | New Home Solar Mandate',
    description: 'California requires solar panels on most new homes. Learn about Title 24 solar requirements, exceptions, and how compliance is verified.',
    tags: ['Solar', 'Compliance'],
    content: `## Title 24 Solar Requirements for New Homes

Since 2020, California has required solar photovoltaic systems on most new residential construction. This mandate, part of the Title 24 Building Energy Efficiency Standards, makes California the first state in the nation to require solar on new homes.

## What Does the Solar Mandate Require?

The Title 24 solar requirement applies to all new single-family homes, duplexes, and low-rise multifamily buildings (three stories or fewer). The minimum system size is calculated based on the home's conditioned floor area and climate zone. For a typical single-family home, this usually means a 2-4 kW system.

## Are There Exceptions?

Yes. Homes with significant roof shading from existing structures or trees may qualify for a reduction or exemption. Properties where the annual solar access is less than 80 percent of optimal can also receive adjustments. Additionally, homes in certain climate zones with community shared solar programs may use off-site solar to meet the requirement.

## How Is Solar Compliance Verified?

Solar compliance is documented on the CF1R energy compliance report and verified through building department plan review. The installed system must match or exceed the specifications in the compliance documents. Final inspection confirms the system is installed and operational before certificate of occupancy is issued.
`,
  },
  'what-is-a-cf1r': {
    title: 'What Is a CF1R? The First Step in Title 24 Compliance',
    seoTitle: 'What Is a CF1R Form California | Title 24 Compliance Report',
    description: 'The CF1R is the foundation of Title 24 compliance. Learn what it is, who prepares it, and why it matters for your California construction project.',
    tags: ['Forms', 'Compliance'],
    content: `## What Is a CF1R?

The CF1R, or Certificate of Compliance, is the first document in California's Title 24 energy compliance chain. It is an energy model and report generated by an energy consultant that demonstrates how a proposed building design will meet or exceed the state's energy efficiency standards.

## Who Prepares the CF1R?

The CF1R is typically prepared by a Title 24 energy consultant using approved compliance software such as CBECC-Res for residential projects or CBECC-Com for commercial buildings. The consultant models the building's envelope, HVAC systems, water heating, lighting, and solar to produce a report showing code compliance.

## What Does the CF1R Include?

The CF1R includes the building's energy budget calculations, a list of required HERS or ECC verification measures (CF3R items), specifications for installed equipment, insulation R-values, window U-factors and SHGC ratings, and duct system requirements. It serves as the blueprint that contractors must follow and verifiers must check against.

## Why the CF1R Matters for Your Project

Without an approved CF1R, your building permit will not be issued. The CF1R also determines which field verification tests your project will require. Getting the CF1R done early allows your team to plan for inspections, order the right equipment, and avoid costly change orders later in construction.
`,
  },
  'duct-leakage-testing': {
    title: 'Duct Leakage Testing: What It Is and Why It Matters',
    seoTitle: 'Duct Leakage Testing California | Title 24 HERS Verification',
    description: 'Duct leakage testing is one of the most common Title 24 HERS verification measures. Learn how it works, what the limits are, and how to pass.',
    tags: ['HERS', 'Testing'],
    content: `## What Is Duct Leakage Testing?

Duct leakage testing is a diagnostic procedure that measures how much conditioned air escapes from your HVAC ductwork before reaching the living space. In California, duct leakage testing is one of the most frequently required HERS verification measures under Title 24.

## How Is Duct Leakage Measured?

A HERS rater uses a calibrated fan and pressure gauge called a duct blaster to pressurize the duct system to 25 Pascals. The fan speed required to maintain that pressure indicates the leakage rate, measured in cubic feet per minute (CFM25). This value is then compared against the maximum allowed by the CF1R energy compliance report.

## What Are the Leakage Limits?

For new construction in California, total duct leakage must typically not exceed 4 percent of the nominal system airflow. For HVAC replacements and alterations, the requirement may be 8 percent or 15 percent depending on the scope of work and accessibility of the duct system.

## Tips for Passing Duct Leakage Testing

Seal all duct joints with mastic or approved tape before the test. Pay special attention to connections at the air handler, register boots, and takeoffs. Flex duct connections should be secured with zip ties and sealed with mastic. Schedule the test before drywall is installed so any leaks can be easily located and repaired.
`,
  },
  'heat-pump-water-heater-title-24': {
    title: 'Heat Pump Water Heaters and Title 24 Compliance',
    seoTitle: 'Heat Pump Water Heater Title 24 California | Compliance Guide',
    description: 'Heat pump water heaters are increasingly required by Title 24. Learn about the requirements, energy savings, and compliance verification process.',
    tags: ['Compliance', 'HERS'],
    content: `## Heat Pump Water Heaters and Title 24

California's 2025 Energy Code strongly favors heat pump water heaters (HPWHs) for new residential construction. Under the updated Title 24 standards, heat pump water heaters are the baseline technology for calculating energy budgets, making them effectively required for most new homes unless designers offset the penalty of using a less efficient system elsewhere.

## Why Heat Pump Water Heaters?

Heat pump water heaters use electricity to move heat from the surrounding air into the water tank, making them two to three times more energy efficient than conventional electric resistance or gas water heaters. This efficiency gain is critical for meeting California's aggressive energy and carbon reduction goals.

## Title 24 Verification Requirements

When a heat pump water heater is installed, the HERS or ECC rater may need to verify proper installation including correct placement for adequate airflow, proper condensate drainage, appropriate electrical connections, and that the unit matches the specifications listed on the CF1R compliance report. Some installations also require verification of the dedicated 240-volt circuit and proper clearances.

## Installation Considerations

Heat pump water heaters need adequate airspace around them to operate efficiently. California's building code requires a minimum room volume or louvered door for enclosed installations. They also produce cool, dehumidified air as a byproduct, which can be beneficial in warm climates but should be considered in cooler regions.
`,
  },
  'performance-path-title-24': {
    title: 'Performance Path vs. Prescriptive Path: Title 24 Compliance Methods',
    seoTitle: 'Performance vs Prescriptive Path Title 24 | California Energy Code',
    description: 'California Title 24 offers two compliance approaches. Learn the difference between performance and prescriptive paths and which is right for your project.',
    tags: ['Compliance'],
    content: `## Performance Path vs. Prescriptive Path

California's Title 24 energy code offers two methods for demonstrating compliance: the prescriptive path and the performance path. Understanding the difference is important for builders, architects, and energy consultants because the choice affects design flexibility, cost, and the verification measures required.

## What Is the Prescriptive Path?

The prescriptive path is a checklist approach. It specifies exact minimum requirements for each building component: insulation R-values, window U-factors, HVAC efficiency ratings, lighting power density, and more. If every component meets or exceeds the prescribed value, the building complies. No energy modeling is required.

## What Is the Performance Path?

The performance path uses computer energy modeling to demonstrate that the proposed building design will use equal or less energy than a standard reference design. This approach allows trade-offs between building components. For example, a designer might use higher-performance windows to offset lower insulation values, as long as the total energy budget is met.

## Which Path Should You Choose?

The prescriptive path is simpler but less flexible. It works well for straightforward projects with standard designs. The performance path requires an energy consultant and modeling software but offers significantly more design freedom. Most custom homes and larger projects use the performance path because it allows optimization and often results in lower construction costs through strategic trade-offs.
`,
  },
  'hvac-replacement-hers-rater': {
    title: 'Do You Need a HERS Rater for an HVAC Replacement?',
    seoTitle: 'HERS Rater for HVAC Replacement California | When Is It Required?',
    description: 'Replacing your HVAC system in California? Learn when Title 24 requires a HERS rater inspection and what to expect during the verification process.',
    tags: ['HERS', 'HVAC'],
    content: `## Do You Need a HERS Rater for an HVAC Replacement?

In most cases, yes. California's Title 24 energy code requires HERS verification for HVAC system replacements in existing homes. When you replace a furnace, air conditioner, or heat pump, a certified HERS or ECC rater must verify that the new system is installed correctly and meets energy code requirements.

## What Does the HERS Rater Check?

For a typical HVAC replacement, the HERS rater will verify refrigerant charge to ensure the system has the correct amount of refrigerant for optimal efficiency, airflow across the indoor coil to confirm it meets manufacturer specifications, duct leakage to make sure the duct system is adequately sealed, and that the equipment matches what was specified on the compliance documents.

## When Is HERS Verification Required?

HERS verification is required for most HVAC change-outs that require a building permit. This includes replacing a furnace, air conditioner, heat pump, or package unit. Some exceptions exist for like-for-like replacements in certain situations, but the trend under California's updated energy codes is toward more verification, not less.

## How to Prepare for the Inspection

Make sure your HVAC contractor pulls the proper permits and files the CF1R before starting work. The contractor should complete and sign the CF2R installer certificate after installation. Then schedule the HERS rater to perform the CF3R verification. Having all paperwork in order before the rater arrives will help the inspection go smoothly and avoid delays in closing out the permit.
`,
  },
}


export async function generateStaticParams() {
  return Object.keys(articles).map(slug => ({ slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const article = articles[slug]
  if (!article) return {}
  return {
    title: article.seoTitle,
    description: article.description,
  }
}

export default async function ResourceArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const article = articles[slug]
  if (!article) notFound()
  const sections = article.content.split(/^## /gm).filter(Boolean)

  return (
    <div className="mx-auto max-w-3xl px-4 pb-20 pt-12 sm:px-6">
      <Breadcrumb items={[
        { label: 'Home', href: '/' },
        { label: 'Resources', href: '/resources' },
        { label: article.title },
      ]} />

      <article>
        <header className="border-t border-ink pt-6">
          <div className="flex flex-wrap gap-1.5">
            {article.tags.map(tag => (
              <span key={tag} className="tag">{tag}</span>
            ))}
          </div>
          <h1 className="mt-3 text-[clamp(1.75rem,3.6vw,2.5rem)] font-bold leading-[1.08]">
            {article.title}
          </h1>
          <p className="mt-4 max-w-[62ch] text-[1.02rem] leading-relaxed">{article.description}</p>
        </header>

        {/* Body copy is capped at 68ch. The old page ran full-width inside a
            max-w-4xl container, which put long-form prose at ~110 characters
            a line — past the point where the eye reliably finds the next one. */}
        <div className="mt-10 space-y-10">
          {sections.map((section, i) => {
            const lines = section.split('\n')
            const heading = lines[0]
            const body = lines.slice(1).join('\n').trim()
            return (
              <section key={i}>
                <h2 className="text-[1.3rem] font-bold leading-snug">{heading}</h2>
                <div className="mt-3 max-w-[68ch] space-y-4 leading-relaxed">
                  {body.split('\n\n').map((paragraph, j) => (
                    <p key={j}>{paragraph}</p>
                  ))}
                </div>
              </section>
            )
          })}
        </div>
      </article>

      <aside className="mt-16 border-t border-ink pt-8">
        <h2 className="text-lg font-bold">Need a rater for this?</h2>
        <p className="mt-2 max-w-[56ch] text-[0.95rem]">
          Search every certified HERS and ECC rater, commissioning agent, and acceptance tester in
          California by city, county, or ZIP.
        </p>
        <div className="mt-5 flex flex-wrap gap-3">
          <Link href="/directory" className="btn-red px-5 py-2.5 text-sm">
            Find a rater
          </Link>
          <Link href="/resources" className="btn-quiet px-5 py-2.5 text-sm">
            More resources
          </Link>
        </div>
      </aside>
    </div>
  )
}
