import { notFound } from 'next/navigation'
import Link from 'next/link'
import type { Metadata } from 'next'

const articles: Record<string, { title: string; seoTitle: string; description: string; tags: string[]; content: string }> = {
  'what-is-a-hers-rater': {
    title: 'What is a HERS Rater? (And When Do You Need One)',
    seoTitle: 'What is a HERS Rater California | Title 24 Directory',
    description: 'Learn what a HERS rater is, why California requires them, and when you need one for your construction or renovation project.',
    tags: ['HERS'],
    content: `## What is a HERS Rater?

A HERS (Home Energy Rating System) rater is a certified professional who inspects and tests a home's energy systems to verify compliance with California's Title 24 energy code. Think of a HERS rater as an energy code inspector â like a structural inspector checks framing, a HERS rater checks your HVAC systems, insulation, ductwork, and windows to make sure everything performs as the plans specify.

## What Does a HERS Rater Actually Do?

During a HERS inspection, the rater performs a series of field tests and visual inspections. The most common measures requiring verification include duct leakage testing, airflow measurement, refrigerant charge verification, insulation inspection, and window verification. HERS raters use pressurization equipment to measure how much air leaks from your HVAC ductwork.

## When Do You Need a HERS Rater in California?

You typically need a HERS rater for new residential construction, HVAC system replacements, home additions over a certain square footage, and major renovations with HVAC work.

## HERS vs ECC: What's Changing in 2026?

Starting with the 2025 California Energy Code, the HERS program is being phased out and replaced by the ECC (Energy Code Compliance) program. The role is essentially the same, but the certification and provider structure is changing.
    `,
  },
  'cf2r-vs-cf3r': {
    title: 'CF2R vs CF3R: What\'s the Difference?',
    seoTitle: 'CF2R vs CF3R Difference | Title 24 California Forms Explained',
    description: 'Confused about CF2R and CF3R forms? Here\'s a clear explanation of the difference between installer certificates and verifier certificates in California Title 24.',
    tags: ['Forms'],
    content: `## CF2R vs CF3R: Understanding Title 24 Compliance Forms

The CF2R is a declaration by the trade contractor that they installed the specified energy measure correctly. The CF3R is the independent verification signed by a certified HERS or ECC rater after they have personally tested and inspected the installation.

## The Title 24 Compliance Document Chain

To understand CF2R and CF3R forms, you first need to understand how Title 24 documentation flows through a construction project. The CF1R is the compliance report, generated by an energy consultant. The CF2R is the installer certificate, and the CF3R is the verifier certificate.

## Why Both Forms Are Required

California's Title 24 compliance system is built on the principle that self-certification alone isn't sufficient for energy measures. The two-step system creates accountability at both the installation and verification levels.
    `,
  },
  'title-24-compliance-guide': {
    title: 'California Title 24 Compliance: A Builder\'s Guide',
    seoTitle: 'California Title 24 Compliance Guide for Builders | Title 24 Directory',
    description: 'A complete guide to California Title 24 energy code compliance for new construction and renovations. Learn what\'s required, who verifies it, and how to stay on schedule.',
    tags: ['Compliance'],
    content: `## California Title 24 Compliance: A Builder's Complete Guide

California's Title 24 Building Energy Efficiency Standards are among the most comprehensive energy codes in the country. For builders, contractors, and developers, understanding what Title 24 requires is essential to keeping projects on schedule.

## What Is Title 24?

Title 24 refers to Part 6 of the California Code of Regulations, which sets minimum energy efficiency standards for all new construction and major renovations in the state.

## The Three Documents Every Project Needs

Title 24 compliance runs on paperwork â specifically, a chain of three documents that must be completed in order: CF1R (Compliance Report), CF2R (Installer Certificate), and CF3R (Verification Certificate).

## How to Keep Your Project on Schedule

Title 24 inspections are a frequent source of construction delays. To stay on track, hire the HERS rater early, brief your trade contractors, schedule insulation inspections before drywall, and get your CF2Rs filed promptly.
    `,
  },
  'what-is-acceptance-testing': {
    title: 'What Does an Acceptance Tester Do?',
    seoTitle: 'Title 24 Acceptance Testing California | What Does an Acceptance Tester Do?',
    description: 'Learn what Title 24 acceptance testing covers in California, when it\'s required, and how to find a certified acceptance tester for your project.',
    tags: ['Compliance'],
    content: `## What Does a Title 24 Acceptance Tester Do?

Acceptance testing is a mandatory part of Title 24 compliance for certain building systems. An acceptance tester is a certified professional who performs standardized functional tests to verify that installed systems operate correctly before a certificate of occupancy is issued.

## What Systems Require Acceptance Testing?

Title 24 acceptance testing covers a range of building systems. The most commonly tested include HVAC controls and economizers, lighting controls, outdoor lighting controls, mechanical ventilation, fault detection and diagnostics, and plumbing controls.

## Who Can Perform Acceptance Testing?

Title 24 acceptance testing must be performed by a certified acceptance test technician (ATT) or an acceptance test employer (ATE). Requirements vary depending on the system being tested and the scope of the project.

## Finding an Acceptance Tester in California

Use our directory to find certified acceptance testers serving your project's location. Filter by the "Acceptance Tester" service type to see qualified professionals in your area.
    `,
  },
  'hers-vs-ecc-rater': {
    title: 'ECC Rater vs HERS Rater: Which Do You Need?',
    seoTitle: 'ECC Rater vs HERS Rater California | Which Do You Need in 2026?',
    description: 'California\'s energy code is changing in 2026. Here\'s the difference between ECC raters and HERS raters and which one your project requires.',
    tags: ['HERS', 'ECC'],
    content: `## ECC Rater vs HERS Rater: Which Do You Need?

If you're starting a California construction project in 2026, you may have heard that HERS raters are being replaced by ECC raters. This change stems from California's new 2025 Energy Code, which replaced the Home Energy Rating System program with the Energy Code Compliance program effective January 1, 2026.

## What Is a HERS Rater?

A HERS (Home Energy Rating System) rater is a certified field verifier who inspects and tests residential buildings to confirm that energy systems comply with California's Title 24 standards.

## What Is an ECC Rater?

An ECC (Energy Code Compliance) rater performs the same fundamental role as a HERS rater but under the new program framework established by the 2025 California Energy Code.

## Which Do You Need?

The answer depends on when your permit was pulled. Projects permitted under the 2022 Energy Code continue to use HERS verification. Projects permitted under the 2025 Energy Code require ECC verification.
    `,
  },
}

export async function generateStaticParams() {
  return Object.keys(articles).map(slug => ({ slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const article = articles[slug]
  if (!article) return {}
  return {
    title: article.seoTitle,
    description: article.description,
    alternates: { canonical: `https://title24directory.com/resources/${slug}` },
  }
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const article = articles[slug]
  if (!article) notFound()

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title,
    description: article.description,
    datePublished: '2026-03-01',
    author: { '@type': 'Organization', name: 'Title24 Directory' },
    publisher: { '@type': 'Organization', name: 'Title24 Directory', url: 'https://title24directory.com' },
  }

  const renderContent = (content: string) => {
    return content.split('\n').map((line, i) => {
      if (line.startsWith('## ')) return <h2 key={i} className="text-2xl font-bold text-gray-900 mt-10 mb-4">{line.slice(3)}</h2>
      if (line.trim() === '') return <div key={i} className="mb-4" />
      return <p key={i} className="text-gray-600 leading-relaxed mb-2">{line}</p>
    })
  }

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <nav className="flex items-center space-x-2 text-sm text-gray-500 mb-6">
        <Link href="/" className="hover:text-blue-700">Home</Link>
        <span>âº</span>
        <Link href="/resources" className="hover:text-blue-700">Resources</Link>
        <span>âº</span>
        <span className="text-gray-900 font-medium">{article.title}</span>
      </nav>
      <div className="flex gap-2 mb-4">
        {article.tags.map(tag => <span key={tag} className="bg-blue-100 text-blue-800 text-xs font-semibold px-2 py-1 rounded">{tag}</span>)}
      </div>
      <h1 className="text-4xl font-bold text-gray-900 mb-8">{article.title}</h1>
      <article className="prose prose-lg max-w-none">
        {renderContent(article.content)}
      </article>
      <div className="mt-12 bg-blue-50 rounded-2xl p-8 text-center">
        <h3 className="text-xl font-bold text-gray-900 mb-2">Ready to find a Title 24 rater?</h3>
        <p className="text-gray-500 mb-4">Search our directory of certified HERS and ECC raters across California.</p>
        <Link href="/directory" className="bg-blue-700 text-white px-6 py-3 rounded-xl font-semibold hover:bg-blue-800 transition-colors inline-block">Search the Directory â</Link>
      </div>
    </div>
  )
}
