export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim()
}

export const CA_COUNTIES = [
  'Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa', 'Contra Costa',
  'Del Norte', 'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Imperial', 'Inyo',
  'Kern', 'Kings', 'Lake', 'Lassen', 'Los Angeles', 'Madera', 'Marin', 'Mariposa',
  'Mendocino', 'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange',
  'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito', 'San Bernardino',
  'San Diego', 'San Francisco', 'San Joaquin', 'San Luis Obispo', 'San Mateo',
  'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou',
  'Solano', 'Sonoma', 'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare',
  'Tuolumne', 'Ventura', 'Yolo', 'Yuba'
].map(name => ({ name, slug: slugify(name) }))

export const CA_CITIES = [
  { name: 'Los Angeles', county: 'Los Angeles' },
  { name: 'Long Beach', county: 'Los Angeles' },
  { name: 'Santa Monica', county: 'Los Angeles' },
  { name: 'Pasadena', county: 'Los Angeles' },
  { name: 'Burbank', county: 'Los Angeles' },
  { name: 'Glendale', county: 'Los Angeles' },
  { name: 'Torrance', county: 'Los Angeles' },
  { name: 'Pomona', county: 'Los Angeles' },
  { name: 'El Monte', county: 'Los Angeles' },
  { name: 'Inglewood', county: 'Los Angeles' },
  { name: 'Downey', county: 'Los Angeles' },
  { name: 'West Covina', county: 'Los Angeles' },
  { name: 'Norwalk', county: 'Los Angeles' },
  { name: 'Compton', county: 'Los Angeles' },
  { name: 'Carson', county: 'Los Angeles' },
  { name: 'Hawthorne', county: 'Los Angeles' },
  { name: 'Alhambra', county: 'Los Angeles' },
  { name: 'Whittier', county: 'Los Angeles' },
  { name: 'Lakewood', county: 'Los Angeles' },
  { name: 'Bellflower', county: 'Los Angeles' },
  { name: 'Baldwin Park', county: 'Los Angeles' },
  { name: 'Arcadia', county: 'Los Angeles' },
  { name: 'Covina', county: 'Los Angeles' },
  { name: 'Redondo Beach', county: 'Los Angeles' },
  { name: 'Manhattan Beach', county: 'Los Angeles' },
  { name: 'Culver City', county: 'Los Angeles' },
  { name: 'Gardena', county: 'Los Angeles' },
  { name: 'Thousand Oaks', county: 'Los Angeles' },
  { name: 'Lancaster', county: 'Los Angeles' },
  { name: 'Palmdale', county: 'Los Angeles' },
  { name: 'San Diego', county: 'San Diego' },
  { name: 'Chula Vista', county: 'San Diego' },
  { name: 'Oceanside', county: 'San Diego' },
  { name: 'Escondido', county: 'San Diego' },
  { name: 'Santee', county: 'San Diego' },
  { name: 'El Cajon', county: 'San Diego' },
  { name: 'Carlsbad', county: 'San Diego' },
  { name: 'Vista', county: 'San Diego' },
  { name: 'San Marcos', county: 'San Diego' },
  { name: 'Encinitas', county: 'San Diego' },
  { name: 'National City', county: 'San Diego' },
  { name: 'La Mesa', county: 'San Diego' },
  { name: 'Poway', county: 'San Diego' },
  { name: 'Lemon Grove', county: 'San Diego' },
  { name: 'Anaheim', county: 'Orange' },
  { name: 'Santa Ana', county: 'Orange' },
  { name: 'Irvine', county: 'Orange' },
  { name: 'Huntington Beach', county: 'Orange' },
  { name: 'Garden Grove', county: 'Orange' },
  { name: 'Fullerton', county: 'Orange' },
  { name: 'Orange', county: 'Orange' },
  { name: 'Costa Mesa', county: 'Orange' },
  { name: 'Mission Viejo', county: 'Orange' },
  { name: 'Newport Beach', county: 'Orange' },
  { name: 'Westminster', county: 'Orange' },
  { name: 'Buena Park', county: 'Orange' },
  { name: 'Lake Forest', county: 'Orange' },
  { name: 'Tustin', county: 'Orange' },
  { name: 'Yorba Linda', county: 'Orange' },
  { name: 'Laguna Niguel', county: 'Orange' },
  { name: 'Fountain Valley', county: 'Orange' },
  { name: 'Aliso Viejo', county: 'Orange' },
  { name: 'Rancho Santa Margarita', county: 'Orange' },
  { name: 'San Clemente', county: 'Orange' },
  { name: 'Riverside', county: 'Riverside' },
  { name: 'Moreno Valley', county: 'Riverside' },
  { name: 'Corona', county: 'Riverside' },
  { name: 'Murrieta', county: 'Riverside' },
  { name: 'Temecula', county: 'Riverside' },
  { name: 'Hemet', county: 'Riverside' },
  { name: 'Menifee', county: 'Riverside' },
  { name: 'Perris', county: 'Riverside' },
  { name: 'Indio', county: 'Riverside' },
  { name: 'Palm Springs', county: 'Riverside' },
  { name: 'Palm Desert', county: 'Riverside' },
  { name: 'Lake Elsinore', county: 'Riverside' },
  { name: 'Cathedral City', county: 'Riverside' },
  { name: 'San Bernardino', county: 'San Bernardino' },
  { name: 'Fontana', county: 'San Bernardino' },
  { name: 'Rancho Cucamonga', county: 'San Bernardino' },
  { name: 'Ontario', county: 'San Bernardino' },
  { name: 'Victorville', county: 'San Bernardino' },
  { name: 'Rialto', county: 'San Bernardino' },
  { name: 'Hesperia', county: 'San Bernardino' },
  { name: 'Chino', county: 'San Bernardino' },
  { name: 'Chino Hills', county: 'San Bernardino' },
  { name: 'Apple Valley', county: 'San Bernardino' },
  { name: 'Redlands', county: 'San Bernardino' },
  { name: 'Upland', county: 'San Bernardino' },
  { name: 'Colton', county: 'San Bernardino' },
  { name: 'San Jose', county: 'Santa Clara' },
  { name: 'Sunnyvale', county: 'Santa Clara' },
  { name: 'Santa Clara', county: 'Santa Clara' },
  { name: 'Fremont', county: 'Alameda' },
  { name: 'Mountain View', county: 'Santa Clara' },
  { name: 'Palo Alto', county: 'Santa Clara' },
  { name: 'Milpitas', county: 'Santa Clara' },
  { name: 'Gilroy', county: 'Santa Clara' },
  { name: 'Campbell', county: 'Santa Clara' },
  { name: 'Cupertino', county: 'Santa Clara' },
  { name: 'Los Gatos', county: 'Santa Clara' },
  { name: 'Morgan Hill', county: 'Santa Clara' },
  { name: 'Los Altos', county: 'Santa Clara' },
  { name: 'Oakland', county: 'Alameda' },
  { name: 'Berkeley', county: 'Alameda' },
  { name: 'Hayward', county: 'Alameda' },
  { name: 'Livermore', county: 'Alameda' },
  { name: 'Pleasanton', county: 'Alameda' },
  { name: 'Union City', county: 'Alameda' },
  { name: 'Newark', county: 'Alameda' },
  { name: 'Dublin', county: 'Alameda' },
  { name: 'Emeryville', county: 'Alameda' },
  { name: 'Sacramento', county: 'Sacramento' },
  { name: 'Elk Grove', county: 'Sacramento' },
  { name: 'Roseville', county: 'Placer' },
  { name: 'Folsom', county: 'Sacramento' },
  { name: 'Citrus Heights', county: 'Sacramento' },
  { name: 'Rancho Cordova', county: 'Sacramento' },
  { name: 'Fresno', county: 'Fresno' },
  { name: 'Clovis', county: 'Fresno' },
  { name: 'Sanger', county: 'Fresno' },
  { name: 'Reedley', county: 'Fresno' },
  { name: 'Madera', county: 'Madera' },
  { name: 'Bakersfield', county: 'Kern' },
  { name: 'Delano', county: 'Kern' },
  { name: 'Ridgecrest', county: 'Kern' },
  { name: 'Concord', county: 'Contra Costa' },
  { name: 'Richmond', county: 'Contra Costa' },
  { name: 'Antioch', county: 'Contra Costa' },
  { name: 'Walnut Creek', county: 'Contra Costa' },
  { name: 'Pittsburg', county: 'Contra Costa' },
  { name: 'Brentwood', county: 'Contra Costa' },
  { name: 'San Ramon', county: 'Contra Costa' },
  { name: 'Danville', county: 'Contra Costa' },
  { name: 'Daly City', county: 'San Mateo' },
  { name: 'South San Francisco', county: 'San Mateo' },
  { name: 'San Mateo', county: 'San Mateo' },
  { name: 'Redwood City', county: 'San Mateo' },
  { name: 'Burlingame', county: 'San Mateo' },
  { name: 'San Bruno', county: 'San Mateo' },
  { name: 'Foster City', county: 'San Mateo' },
  { name: 'Oxnard', county: 'Ventura' },
  { name: 'Simi Valley', county: 'Ventura' },
  { name: 'Ventura', county: 'Ventura' },
  { name: 'Camarillo', county: 'Ventura' },
  { name: 'Moorpark', county: 'Ventura' },
  { name: 'San Luis Obispo', county: 'San Luis Obispo' },
  { name: 'Paso Robles', county: 'San Luis Obispo' },
  { name: 'Atascadero', county: 'San Luis Obispo' },
  { name: 'Santa Barbara', county: 'Santa Barbara' },
  { name: 'Santa Maria', county: 'Santa Barbara' },
  { name: 'Lompoc', county: 'Santa Barbara' },
  { name: 'Salinas', county: 'Monterey' },
  { name: 'Monterey', county: 'Monterey' },
  { name: 'Seaside', county: 'Monterey' },
  { name: 'Modesto', county: 'Stanislaus' },
  { name: 'Turlock', county: 'Stanislaus' },
  { name: 'Ceres', county: 'Stanislaus' },
  { name: 'Merced', county: 'Merced' },
  { name: 'Stockton', county: 'San Joaquin' },
  { name: 'Tracy', county: 'San Joaquin' },
  { name: 'Lodi', county: 'San Joaquin' },
  { name: 'Manteca', county: 'San Joaquin' },
  { name: 'Vallejo', county: 'Solano' },
  { name: 'Fairfield', county: 'Solano' },
  { name: 'Vacaville', county: 'Solano' },
  { name: 'Napa', county: 'Napa' },
  { name: 'Santa Rosa', county: 'Sonoma' },
  { name: 'Petaluma', county: 'Sonoma' },
  { name: 'Rohnert Park', county: 'Sonoma' },
  { name: 'Redding', county: 'Shasta' },
  { name: 'Chico', county: 'Butte' },
  { name: 'El Dorado Hills', county: 'El Dorado' },
  { name: 'South Lake Tahoe', county: 'El Dorado' },
  { name: 'Visalia', county: 'Tulare' },
  { name: 'Porterville', county: 'Tulare' },
  { name: 'Tulare', county: 'Tulare' },
  { name: 'El Centro', county: 'Imperial' },
  { name: 'San Francisco', county: 'San Francisco' },
  { name: 'San Rafael', county: 'Marin' },
  { name: 'Novato', county: 'Marin' },
].map(c => ({
  ...c,
  slug: slugify(c.name),
  county_slug: slugify(c.county),
}))

const seen = new Set<string>()
export const CITIES = CA_CITIES.filter(c => {
  if (seen.has(c.slug)) return false
  seen.add(c.slug)
  return true
})
