export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim()
}

export const CA_COUNTIES = [
  'Alameda', 'Alpine', 'Amador', 'Butte', 'Calaveras', 'Colusa', 'Contra Costa',
  'Del Norte', 'El Dorado', 'Fresno', 'Glenn', 'Humboldt', 'Imperial', 'Inyo',
  'Kern', 'Kings', 'Lake', 'Lassen', 'Los Angeles', 'Madera', 'Marin', 'Mariposa',
  'Mendocino', 'Merced', 'Modoc', 'Mono', 'Monterey', 'Napa', 'Nevada', 'Orange',
  'Placer', 'Plumas', 'Riverside', 'Sacramento', 'San Benito', 'San Bernardino',
  'San Diego', 'San Francisco', 'San Joaquin', 'San Luis Obispo', 'San Mateo',
  'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Shasta', 'Sierra', 'Siskiyou',
  'Solano', 'Sonoma', 'Stanislaus', 'Sutter', 'Tehama', 'Trinity', 'Tulare',
  'Tuolumne', 'Ventura', 'Yolo', 'Yuba'
].map(name => ({ name, slug: slugify(name) }))

export const CA_CITIES = [
  { name: 'Los Angeles', county: 'Los Angeles' },
  { name: 'Long Beach', county: 'Los Angeles' },
  { name: 'Santa Monica', county: 'Los Angeles' },
  { name: 'Pasadena', county: 'Los Angeles' },
  { name: 'Burbank', county: 'Los Angeles' },
  { name: 'Glendale', county: 'Los Angeles' },
  { name: 'Torrance', county: 'Los Angeles' },
  { name: 'Pomona', county: 'Los Angeles' },
  { name: 'El Monte', county: 'Los Angeles' },
  { name: 'Inglewood', county: 'Los Angeles' },
  { name: 'Downey', county: 'Los Angeles' },
  { name: 'West Covina', county: 'Los Angeles' },
  { name: 'Norwalk', county: 'Los Angeles' },
  { name: 'Compton', county: 'Los Angeles' },
  { name: 'Carson', county: 'Los Angeles' },
  { name: 'Hawthorne', county: 'Los Angeles' },
  { name: 'Alhambra', county: 'Los Angeles' },
  { name: 'Whittier', county: 'Los Angeles' },
  { name: 'Lakewood', county: 'Los Angeles' },
  { name: 'Bellflower', county: 'Los Angeles' },
  { name: 'Baldwin Park', county: 'Los Angeles' },
  { name: 'Arcadia', county: 'Los Angeles' },
  { name: 'Covina', county: 'Los Angeles' },
  { name: 'Redondo Beach', county: 'Los Angeles' },
  { name: 'Manhattan Beach', county: 'Los Angeles' },
  { name: 'Culver City', county: 'Los Angeles' },
  { name: 'Gardena', county: 'Los Angeles' },
  { name: 'Lancaster', county: 'Los Angeles' },
  { name: 'Palmdale', county: 'Los Angeles' },
  { name: 'San Diego', county: 'San Diego' },
  { name: 'Chula Vista', county: 'San Diego' },
  { name: 'Oceanside', county: 'San Diego' },
  { name: 'Escondido', county: 'San Diego' },
  { name: 'Santee', county: 'San Diego' },
  { name: 'El Cajon', county: 'San Diego' },
  { name: 'Carlsbad', county: 'San Diego' },
  { name: 'Vista', county: 'San Diego' },
  { name: 'San Marcos', county: 'San Diego' },
  { name: 'Encinitas', county: 'San Diego' },
  { name: 'National City', county: 'San Diego' },
  { name: 'La Mesa', county: 'San Diego' },
  { name: 'Poway', county: 'San Diego' },
  { name: 'Lemon Grove', county: 'San Diego' },
  { name: 'Anaheim', county: 'Orange' },
  { name: 'Santa Ana', county: 'Orange' },
  { name: 'Irvine', county: 'Orange' },
  { name: 'Huntington Beach', county: 'Orange' },
  { name: 'Garden Grove', county: 'Orange' },
  { name: 'Fullerton', county: 'Orange' },
  { name: 'Orange', county: 'Orange' },
  { name: 'Costa Mesa', county: 'Orange' },
  { name: 'Mission Viejo', county: 'Orange' },
  { name: 'Newport Beach', county: 'Orange' },
  { name: 'Westminster', county: 'Orange' },
  { name: 'Buena Park', county: 'Orange' },
  { name: 'Lake Forest', county: 'Orange' },
  { name: 'Tustin', county: 'Orange' },
  { name: 'Yorba Linda', county: 'Orange' },
  { name: 'Laguna Niguel', county: 'Orange' },
  { name: 'Fountain Valley', county: 'Orange' },
  { name: 'Aliso Viejo', county: 'Orange' },
  { name: 'Rancho Santa Margarita', county: 'Orange' },
  { name: 'San Clemente', county: 'Orange' },
  { name: 'Riverside', county: 'Riverside' },
  { name: 'Moreno Valley', county: 'Riverside' },
  { name: 'Corona', county: 'Riverside' },
  { name: 'Murrieta', county: 'Riverside' },
  { name: 'Temecula', county: 'Riverside' },
  { name: 'Hemet', county: 'Riverside' },
  { name: 'Menifee', county: 'Riverside' },
  { name: 'Perris', county: 'Riverside' },
  { name: 'Indio', county: 'Riverside' },
  { name: 'Palm Springs', county: 'Riverside' },
  { name: 'Palm Desert', county: 'Riverside' },
  { name: 'Lake Elsinore', county: 'Riverside' },
  { name: 'Cathedral City', county: 'Riverside' },
  { name: 'San Bernardino', county: 'San Bernardino' },
  { name: 'Fontana', county: 'San Bernardino' },
  { name: 'Rancho Cucamonga', county: 'San Bernardino' },
  { name: 'Ontario', county: 'San Bernardino' },
  { name: 'Victorville', county: 'San Bernardino' },
  { name: 'Rialto', county: 'San Bernardino' },
  { name: 'Hesperia', county: 'San Bernardino' },
  { name: 'Chino', county: 'San Bernardino' },
  { name: 'Chino Hills', county: 'San Bernardino' },
  { name: 'Apple Valley', county: 'San Bernardino' },
  { name: 'Redlands', county: 'San Bernardino' },
  { name: 'Upland', county: 'San Bernardino' },
  { name: 'Colton', county: 'San Bernardino' },
  { name: 'San Jose', county: 'Santa Clara' },
  { name: 'Sunnyvale', county: 'Santa Clara' },
  { name: 'Santa Clara', county: 'Santa Clara' },
  { name: 'Fremont', county: 'Alameda' },
  { name: 'Mountain View', county: 'Santa Clara' },
  { name: 'Palo Alto', county: 'Santa Clara' },
  { name: 'Milpitas', county: 'Santa Clara' },
  { name: 'Gilroy', county: 'Santa Clara' },
  { name: 'Campbell', county: 'Santa Clara' },
  { name: 'Cupertino', county: 'Santa Clara' },
  { name: 'Los Gatos', county: 'Santa Clara' },
  { name: 'Morgan Hill', county: 'Santa Clara' },
  { name: 'Los Altos', county: 'Santa Clara' },
  { name: 'Oakland', county: 'Alameda' },
  { name: 'Berkeley', county: 'Alameda' },
  { name: 'Hayward', county: 'Alameda' },
  { name: 'Livermore', county: 'Alameda' },
  { name: 'Pleasanton', county: 'Alameda' },
  { name: 'Union City', county: 'Alameda' },
  { name: 'Newark', county: 'Alameda' },
  { name: 'Dublin', county: 'Alameda' },
  { name: 'Emeryville', county: 'Alameda' },
  { name: 'Sacramento', county: 'Sacramento' },
  { name: 'Elk Grove', county: 'Sacramento' },
  { name: 'Roseville', county: 'Placer' },
  { name: 'Folsom', county: 'Sacramento' },
  { name: 'Citrus Heights', county: 'Sacramento' },
  { name: 'Rancho Cordova', county: 'Sacramento' },
  { name: 'Fresno', county: 'Fresno' },
  { name: 'Clovis', county: 'Fresno' },
  { name: 'Sanger', county: 'Fresno' },
  { name: 'Reedley', county: 'Fresno' },
  { name: 'Madera', county: 'Madera' },
  { name: 'Bakersfield', county: 'Kern' },
  { name: 'Delano', county: 'Kern' },
  { name: 'Ridgecrest', county: 'Kern' },
  { name: 'Concord', county: 'Contra Costa' },
  { name: 'Richmond', county: 'Contra Costa' },
  { name: 'Antioch', county: 'Contra Costa' },
  { name: 'Walnut Creek', county: 'Contra Costa' },
  { name: 'Pittsburg', county: 'Contra Costa' },
  { name: 'Brentwood', county: 'Contra Costa' },
  { name: 'San Ramon', county: 'Contra Costa' },
  { name: 'Danville', county: 'Contra Costa' },
  { name: 'Daly City', county: 'San Mateo' },
  { name: 'South San Francisco', county: 'San Mateo' },
  { name: 'San Mateo', county: 'San Mateo' },
  { name: 'Redwood City', county: 'San Mateo' },
  { name: 'Burlingame', county: 'San Mateo' },
  { name: 'San Bruno', county: 'San Mateo' },
  { name: 'Foster City', county: 'San Mateo' },
  { name: 'Oxnard', county: 'Ventura' },
  { name: 'Simi Valley', county: 'Ventura' },
  { name: 'Ventura', county: 'Ventura' },
  { name: 'Camarillo', county: 'Ventura' },
  { name: 'Moorpark', county: 'Ventura' },
  { name: 'San Luis Obispo', county: 'San Luis Obispo' },
  { name: 'Paso Robles', county: 'San Luis Obispo' },
  { name: 'Atascadero', county: 'San Luis Obispo' },
  { name: 'Santa Barbara', county: 'Santa Barbara' },
  { name: 'Santa Maria', county: 'Santa Barbara' },
  { name: 'Lompoc', county: 'Santa Barbara' },
  { name: 'Salinas', county: 'Monterey' },
  { name: 'Monterey', county: 'Monterey' },
  { name: 'Seaside', county: 'Monterey' },
  { name: 'Modesto', county: 'Stanislaus' },
  { name: 'Turlock', county: 'Stanislaus' },
  { name: 'Ceres', county: 'Stanislaus' },
  { name: 'Merced', county: 'Merced' },
  { name: 'Stockton', county: 'San Joaquin' },
  { name: 'Tracy', county: 'San Joaquin' },
  { name: 'Lodi', county: 'San Joaquin' },
  { name: 'Manteca', county: 'San Joaquin' },
  { name: 'Vallejo', county: 'Solano' },
  { name: 'Fairfield', county: 'Solano' },
  { name: 'Vacaville', county: 'Solano' },
  { name: 'Napa', county: 'Napa' },
  { name: 'Santa Rosa', county: 'Sonoma' },
  { name: 'Petaluma', county: 'Sonoma' },
  { name: 'Rohnert Park', county: 'Sonoma' },
  { name: 'Redding', county: 'Shasta' },
  { name: 'Chico', county: 'Butte' },
  { name: 'El Dorado Hills', county: 'El Dorado' },
  { name: 'South Lake Tahoe', county: 'El Dorado' },
  { name: 'Visalia', county: 'Tulare' },
  { name: 'Porterville', county: 'Tulare' },
  { name: 'Tulare', county: 'Tulare' },
  { name: 'El Centro', county: 'Imperial' },
  { name: 'San Francisco', county: 'San Francisco' },
  { name: 'San Rafael', county: 'Marin' },
  { name: 'Novato', county: 'Marin' },
  // Los Angeles County
  { name: 'Santa Clarita', county: 'Los Angeles' },
  { name: 'South Gate', county: 'Los Angeles' },
  { name: 'Monterey Park', county: 'Los Angeles' },
  { name: 'Glendora', county: 'Los Angeles' },
  { name: 'Huntington Park', county: 'Los Angeles' },
  { name: 'Lynwood', county: 'Los Angeles' },
  { name: 'Montebello', county: 'Los Angeles' },
  { name: 'Pico Rivera', county: 'Los Angeles' },
  { name: 'Bell Gardens', county: 'Los Angeles' },
  { name: 'Paramount', county: 'Los Angeles' },
  { name: 'Rosemead', county: 'Los Angeles' },
  { name: 'San Gabriel', county: 'Los Angeles' },
  { name: 'Temple City', county: 'Los Angeles' },
  { name: 'Azusa', county: 'Los Angeles' },
  { name: 'La Mirada', county: 'Los Angeles' },
  { name: 'Cerritos', county: 'Los Angeles' },
  { name: 'Diamond Bar', county: 'Los Angeles' },
  { name: 'Walnut', county: 'Los Angeles' },
  { name: 'Claremont', county: 'Los Angeles' },
  { name: 'San Dimas', county: 'Los Angeles' },
  { name: 'La Verne', county: 'Los Angeles' },
  { name: 'Monrovia', county: 'Los Angeles' },
  { name: 'Duarte', county: 'Los Angeles' },
  { name: 'Sierra Madre', county: 'Los Angeles' },
  { name: 'South Pasadena', county: 'Los Angeles' },
  { name: 'Beverly Hills', county: 'Los Angeles' },
  { name: 'West Hollywood', county: 'Los Angeles' },
  { name: 'Malibu', county: 'Los Angeles' },
  { name: 'Calabasas', county: 'Los Angeles' },
  { name: 'Agoura Hills', county: 'Los Angeles' },
  { name: 'Santa Fe Springs', county: 'Los Angeles' },
  { name: 'Bell', county: 'Los Angeles' },
  { name: 'Maywood', county: 'Los Angeles' },
  { name: 'Cudahy', county: 'Los Angeles' },
  { name: 'Artesia', county: 'Los Angeles' },
  { name: 'Hawaiian Gardens', county: 'Los Angeles' },
  { name: 'Lawndale', county: 'Los Angeles' },
  { name: 'Lomita', county: 'Los Angeles' },
  { name: 'Rancho Palos Verdes', county: 'Los Angeles' },
  { name: 'Palos Verdes Estates', county: 'Los Angeles' },
  { name: 'Rolling Hills Estates', county: 'Los Angeles' },
  { name: 'El Segundo', county: 'Los Angeles' },
  { name: 'Hermosa Beach', county: 'Los Angeles' },
  { name: 'Signal Hill', county: 'Los Angeles' },
  { name: 'Commerce', county: 'Los Angeles' },
  { name: 'La Puente', county: 'Los Angeles' },
  { name: 'San Fernando', county: 'Los Angeles' },
  { name: 'La Canada Flintridge', county: 'Los Angeles' },
  { name: 'Westlake Village', county: 'Los Angeles' },
  { name: 'Hidden Hills', county: 'Los Angeles' },
  { name: 'Irwindale', county: 'Los Angeles' },
  { name: 'Bradbury', county: 'Los Angeles' },
  { name: 'Rolling Hills', county: 'Los Angeles' },
  { name: 'Vernon', county: 'Los Angeles' },
  { name: 'Avalon', county: 'Los Angeles' },
  // Ventura County
  { name: 'Thousand Oaks', county: 'Ventura' },
  { name: 'Port Hueneme', county: 'Ventura' },
  { name: 'Fillmore', county: 'Ventura' },
  { name: 'Santa Paula', county: 'Ventura' },
  { name: 'Ojai', county: 'Ventura' },
  // Orange County
  { name: 'La Habra', county: 'Orange' },
  { name: 'Placentia', county: 'Orange' },
  { name: 'Cypress', county: 'Orange' },
  { name: 'Stanton', county: 'Orange' },
  { name: 'Los Alamitos', county: 'Orange' },
  { name: 'Seal Beach', county: 'Orange' },
  { name: 'Laguna Beach', county: 'Orange' },
  { name: 'Laguna Hills', county: 'Orange' },
  { name: 'Laguna Woods', county: 'Orange' },
  { name: 'Dana Point', county: 'Orange' },
  { name: 'San Juan Capistrano', county: 'Orange' },
  { name: 'Villa Park', county: 'Orange' },
  { name: 'Brea', county: 'Orange' },
  // Riverside County
  { name: 'Jurupa Valley', county: 'Riverside' },
  { name: 'Eastvale', county: 'Riverside' },
  { name: 'Norco', county: 'Riverside' },
  { name: 'Banning', county: 'Riverside' },
  { name: 'Beaumont', county: 'Riverside' },
  { name: 'Wildomar', county: 'Riverside' },
  { name: 'Canyon Lake', county: 'Riverside' },
  { name: 'Calimesa', county: 'Riverside' },
  { name: 'Coachella', county: 'Riverside' },
  { name: 'Desert Hot Springs', county: 'Riverside' },
  { name: 'La Quinta', county: 'Riverside' },
  { name: 'Rancho Mirage', county: 'Riverside' },
  { name: 'Indian Wells', county: 'Riverside' },
  { name: 'Blythe', county: 'Riverside' },
  { name: 'San Jacinto', county: 'Riverside' },
  // San Bernardino County
  { name: 'Yucaipa', county: 'San Bernardino' },
  { name: 'Highland', county: 'San Bernardino' },
  { name: 'Loma Linda', county: 'San Bernardino' },
  { name: 'Montclair', county: 'San Bernardino' },
  { name: 'Adelanto', county: 'San Bernardino' },
  { name: 'Barstow', county: 'San Bernardino' },
  { name: 'Twentynine Palms', county: 'San Bernardino' },
  { name: 'Yucca Valley', county: 'San Bernardino' },
  { name: 'Grand Terrace', county: 'San Bernardino' },
  { name: 'Big Bear Lake', county: 'San Bernardino' },
  { name: 'Needles', county: 'San Bernardino' },
  // San Diego County
  { name: 'Imperial Beach', county: 'San Diego' },
  { name: 'Coronado', county: 'San Diego' },
  { name: 'Del Mar', county: 'San Diego' },
  { name: 'Solana Beach', county: 'San Diego' },
  // Alameda County
  { name: 'Alameda', county: 'Alameda' },
  { name: 'San Leandro', county: 'Alameda' },
  { name: 'Albany', county: 'Alameda' },
  { name: 'Piedmont', county: 'Alameda' },
  // Contra Costa County
  { name: 'Martinez', county: 'Contra Costa' },
  { name: 'Pleasant Hill', county: 'Contra Costa' },
  { name: 'Lafayette', county: 'Contra Costa' },
  { name: 'Orinda', county: 'Contra Costa' },
  { name: 'Moraga', county: 'Contra Costa' },
  { name: 'Hercules', county: 'Contra Costa' },
  { name: 'Pinole', county: 'Contra Costa' },
  { name: 'San Pablo', county: 'Contra Costa' },
  { name: 'El Cerrito', county: 'Contra Costa' },
  { name: 'Oakley', county: 'Contra Costa' },
  { name: 'Clayton', county: 'Contra Costa' },
  // Santa Clara County
  { name: 'Saratoga', county: 'Santa Clara' },
  { name: 'Monte Sereno', county: 'Santa Clara' },
  // San Mateo County
  { name: 'Menlo Park', county: 'San Mateo' },
  { name: 'East Palo Alto', county: 'San Mateo' },
  { name: 'Belmont', county: 'San Mateo' },
  { name: 'San Carlos', county: 'San Mateo' },
  { name: 'Millbrae', county: 'San Mateo' },
  { name: 'Pacifica', county: 'San Mateo' },
  { name: 'Half Moon Bay', county: 'San Mateo' },
  { name: 'Atherton', county: 'San Mateo' },
  { name: 'Hillsborough', county: 'San Mateo' },
  { name: 'Woodside', county: 'San Mateo' },
  { name: 'Portola Valley', county: 'San Mateo' },
  { name: 'Brisbane', county: 'San Mateo' },
  { name: 'Colma', county: 'San Mateo' },
  // Santa Cruz County
  { name: 'Santa Cruz', county: 'Santa Cruz' },
  { name: 'Watsonville', county: 'Santa Cruz' },
  { name: 'Scotts Valley', county: 'Santa Cruz' },
  { name: 'Capitola', county: 'Santa Cruz' },
  // Yolo County
  { name: 'Davis', county: 'Yolo' },
  { name: 'Woodland', county: 'Yolo' },
  { name: 'West Sacramento', county: 'Yolo' },
  { name: 'Winters', county: 'Yolo' },
  // Sutter County
  { name: 'Yuba City', county: 'Sutter' },
  { name: 'Live Oak', county: 'Sutter' },
  // Yuba County
  { name: 'Marysville', county: 'Yuba' },
  { name: 'Wheatland', county: 'Yuba' },
  // Placer County
  { name: 'Rocklin', county: 'Placer' },
  { name: 'Lincoln', county: 'Placer' },
  { name: 'Auburn', county: 'Placer' },
  { name: 'Colfax', county: 'Placer' },
  { name: 'Loomis', county: 'Placer' },
  // Solano County
  { name: 'Benicia', county: 'Solano' },
  { name: 'Suisun City', county: 'Solano' },
  { name: 'Dixon', county: 'Solano' },
  { name: 'Rio Vista', county: 'Solano' },
  // Sonoma County
  { name: 'Windsor', county: 'Sonoma' },
  { name: 'Healdsburg', county: 'Sonoma' },
  { name: 'Sonoma', county: 'Sonoma' },
  { name: 'Cotati', county: 'Sonoma' },
  { name: 'Sebastopol', county: 'Sonoma' },
  { name: 'Cloverdale', county: 'Sonoma' },
  // Marin County
  { name: 'Mill Valley', county: 'Marin' },
  { name: 'San Anselmo', county: 'Marin' },
  { name: 'Larkspur', county: 'Marin' },
  { name: 'Corte Madera', county: 'Marin' },
  { name: 'Sausalito', county: 'Marin' },
  { name: 'Tiburon', county: 'Marin' },
  { name: 'Fairfax', county: 'Marin' },
  { name: 'Ross', county: 'Marin' },
  { name: 'Belvedere', county: 'Marin' },
  // Napa County
  { name: 'American Canyon', county: 'Napa' },
  { name: 'St. Helena', county: 'Napa' },
  { name: 'Calistoga', county: 'Napa' },
  { name: 'Yountville', county: 'Napa' },
  // Monterey County
  { name: 'Marina', county: 'Monterey' },
  { name: 'Pacific Grove', county: 'Monterey' },
  { name: 'Carmel-by-the-Sea', county: 'Monterey' },
  { name: 'Soledad', county: 'Monterey' },
  { name: 'Greenfield', county: 'Monterey' },
  { name: 'King City', county: 'Monterey' },
  { name: 'Gonzales', county: 'Monterey' },
  // Kern County
  { name: 'Tehachapi', county: 'Kern' },
  { name: 'Wasco', county: 'Kern' },
  { name: 'Shafter', county: 'Kern' },
  { name: 'Arvin', county: 'Kern' },
  { name: 'California City', county: 'Kern' },
  { name: 'Taft', county: 'Kern' },
  { name: 'McFarland', county: 'Kern' },
  { name: 'Maricopa', county: 'Kern' },
  // Fresno County
  { name: 'Selma', county: 'Fresno' },
  { name: 'Kerman', county: 'Fresno' },
  { name: 'Coalinga', county: 'Fresno' },
  { name: 'Firebaugh', county: 'Fresno' },
  { name: 'Kingsburg', county: 'Fresno' },
  { name: 'Parlier', county: 'Fresno' },
  { name: 'Fowler', county: 'Fresno' },
  { name: 'Mendota', county: 'Fresno' },
  { name: 'Huron', county: 'Fresno' },
  { name: 'Orange Cove', county: 'Fresno' },
  { name: 'San Joaquin', county: 'Fresno' },
  // Tulare County
  { name: 'Dinuba', county: 'Tulare' },
  { name: 'Lindsay', county: 'Tulare' },
  { name: 'Exeter', county: 'Tulare' },
  { name: 'Farmersville', county: 'Tulare' },
  { name: 'Woodlake', county: 'Tulare' },
  // Kings County
  { name: 'Hanford', county: 'Kings' },
  { name: 'Lemoore', county: 'Kings' },
  { name: 'Corcoran', county: 'Kings' },
  { name: 'Avenal', county: 'Kings' },
  // Madera County
  { name: 'Chowchilla', county: 'Madera' },
  // Merced County
  { name: 'Los Banos', county: 'Merced' },
  { name: 'Atwater', county: 'Merced' },
  { name: 'Livingston', county: 'Merced' },
  { name: 'Dos Palos', county: 'Merced' },
  { name: 'Gustine', county: 'Merced' },
  // Stanislaus County
  { name: 'Riverbank', county: 'Stanislaus' },
  { name: 'Oakdale', county: 'Stanislaus' },
  { name: 'Patterson', county: 'Stanislaus' },
  { name: 'Newman', county: 'Stanislaus' },
  { name: 'Hughson', county: 'Stanislaus' },
  { name: 'Waterford', county: 'Stanislaus' },
  // San Joaquin County
  { name: 'Ripon', county: 'San Joaquin' },
  { name: 'Escalon', county: 'San Joaquin' },
  // Imperial County
  { name: 'Calexico', county: 'Imperial' },
  { name: 'Brawley', county: 'Imperial' },
  { name: 'Imperial', county: 'Imperial' },
  { name: 'Holtville', county: 'Imperial' },
  { name: 'Westmorland', county: 'Imperial' },
  { name: 'Calipatria', county: 'Imperial' },
  // Butte County
  { name: 'Paradise', county: 'Butte' },
  { name: 'Oroville', county: 'Butte' },
  { name: 'Gridley', county: 'Butte' },
  { name: 'Biggs', county: 'Butte' },
  // Shasta County
  { name: 'Anderson', county: 'Shasta' },
  { name: 'Shasta Lake', county: 'Shasta' },
  // El Dorado County
  { name: 'Placerville', county: 'El Dorado' },
  // Nevada County
  { name: 'Grass Valley', county: 'Nevada' },
  { name: 'Nevada City', county: 'Nevada' },
  { name: 'Truckee', county: 'Nevada' },
  // Humboldt County
  { name: 'Eureka', county: 'Humboldt' },
  { name: 'Arcata', county: 'Humboldt' },
  { name: 'Fortuna', county: 'Humboldt' },
  { name: 'Rio Dell', county: 'Humboldt' },
  { name: 'Ferndale', county: 'Humboldt' },
  { name: 'Blue Lake', county: 'Humboldt' },
  { name: 'Trinidad', county: 'Humboldt' },
  // Mendocino County
  { name: 'Ukiah', county: 'Mendocino' },
  { name: 'Fort Bragg', county: 'Mendocino' },
  { name: 'Willits', county: 'Mendocino' },
  { name: 'Point Arena', county: 'Mendocino' },
  // Lake County
  { name: 'Clearlake', county: 'Lake' },
  { name: 'Lakeport', county: 'Lake' },
  // Tehama County
  { name: 'Red Bluff', county: 'Tehama' },
  { name: 'Corning', county: 'Tehama' },
  { name: 'Tehama', county: 'Tehama' },
  // Siskiyou County
  { name: 'Yreka', county: 'Siskiyou' },
  { name: 'Mount Shasta', county: 'Siskiyou' },
  { name: 'Weed', county: 'Siskiyou' },
  { name: 'Dunsmuir', county: 'Siskiyou' },
  { name: 'Tulelake', county: 'Siskiyou' },
  { name: 'Etna', county: 'Siskiyou' },
  { name: 'Fort Jones', county: 'Siskiyou' },
  { name: 'Montague', county: 'Siskiyou' },
  { name: 'Dorris', county: 'Siskiyou' },
  // San Luis Obispo County
  { name: 'Arroyo Grande', county: 'San Luis Obispo' },
  { name: 'Grover Beach', county: 'San Luis Obispo' },
  { name: 'Pismo Beach', county: 'San Luis Obispo' },
  { name: 'Morro Bay', county: 'San Luis Obispo' },
  // Santa Barbara County
  { name: 'Goleta', county: 'Santa Barbara' },
  { name: 'Carpinteria', county: 'Santa Barbara' },
  { name: 'Buellton', county: 'Santa Barbara' },
  { name: 'Solvang', county: 'Santa Barbara' },
  { name: 'Guadalupe', county: 'Santa Barbara' },
  // San Benito County
  { name: 'Hollister', county: 'San Benito' },
  { name: 'San Juan Bautista', county: 'San Benito' },
  // Amador County
  { name: 'Jackson', county: 'Amador' },
  { name: 'Sutter Creek', county: 'Amador' },
  { name: 'Ione', county: 'Amador' },
  { name: 'Plymouth', county: 'Amador' },
  { name: 'Amador City', county: 'Amador' },
  // Calaveras County
  { name: 'Angels Camp', county: 'Calaveras' },
  // Tuolumne County
  { name: 'Sonora', county: 'Tuolumne' },
  // Inyo County
  { name: 'Bishop', county: 'Inyo' },
  // Mono County
  { name: 'Mammoth Lakes', county: 'Mono' },
  // Colusa County
  { name: 'Colusa', county: 'Colusa' },
  { name: 'Williams', county: 'Colusa' },
  // Glenn County
  { name: 'Willows', county: 'Glenn' },
  { name: 'Orland', county: 'Glenn' },
  // Del Norte County
  { name: 'Crescent City', county: 'Del Norte' },
  // Lassen County
  { name: 'Susanville', county: 'Lassen' },
  // Modoc County
  { name: 'Alturas', county: 'Modoc' },
  // Plumas County
  { name: 'Portola', county: 'Plumas' },
  // Sierra County
  { name: 'Loyalton', county: 'Sierra' },
].map(c => ({
  ...c,
  slug: slugify(c.name),
  county_slug: slugify(c.county),
}))

const seen = new Set<string>()
export const CITIES = CA_CITIES.filter(c => {
  if (seen.has(c.slug)) return false
  seen.add(c.slug)
  return true
})

// ---- slug -> display-name lookups -------------------------------------
// Listings store slugs (that is what the Get Listed form submits and what the
// city/county page queries match on). These turn them back into labels.
const COUNTY_BY_SLUG = new Map(CA_COUNTIES.map(c => [c.slug, c.name]))
const CITY_BY_SLUG   = new Map(CITIES.map(c => [c.slug, c.name]))

export function countyName(slug: string): string {
  return COUNTY_BY_SLUG.get(slug) ?? slug
}

export function cityName(slug: string): string {
  return CITY_BY_SLUG.get(slug) ?? slug
}
